<?php
/*------------------------------------------------------------------------
 # SM Shop By - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
	<?php if (!$this->getRequest()->isAjax()): ?>
		<div id="ajax-errors" style="display: none;">
			<ul class="messages">
				<li class="error-msg">
					<ul>
						<li><span><?php echo $this->__('An error occurred, please try again later.'); ?></span></li>
					</ul>
				</li>
			</ul>
		</div>
		<div id="loading" style="display: none; margin-bottom: 10px; text-align: center;">
			<img class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/loader-shopby.gif'); ?>"> <?php echo $this->__('Loading, please wait...'); ?>
		</div>
		<div id="catalog-listing">
	<?php endif; ?>
	<div class="category-products">

		<div class="toolbar-top">
			<?php echo $this->getToolbarHtml() ?>
		</div>

		<div class="yt-products-container clearfix">
			<?php if($this->getMode()!='grid'): ?>
				<?php $_iterator = 0; ?>
				<ol class="products-list" >
					<?php
					$count_input_qty = 0;
					foreach ($_productCollection as $_product):
						$count_input_qty++;
						$now = date("Y-m-d");
						$newsFrom= substr($_product->getData('news_from_date'),0,10);
						$newsTo=  substr($_product->getData('news_to_date'),0,10);
						$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
						$price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice();
						$saleoff= round(($price - $specialprice)/$price*100) ;
						?>
						<li class="item <?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
							<div class="item-inner">
								<div class="product-list-left col-lg-4 col-md-4 col-sm-5 col-xs-12">
									<div class="product-image">
										<a href="<?php echo $_product->getProductUrl() ?>" class="product-img" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
											<img id="product-collection-image-<?php echo $_product->getId(); ?>"
												 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,300); ?>"
												 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										</a>

										<?php if ( $now>=$newsFrom && $now<=$newsTo ){ ?>
										<span class="new-product have-ico"><?php echo $this->__('New'); ?></span>
										<?php }
										/*  if ( $specialprice ){ */?><!--
								<span class="sale-product have-ico"><?php /*echo $this->__('Sale'); */?></span>
							--><?php /*} */?>
										<?php if($_product->getKitnekaaOffers()){ ?>
											<?php
											$offer=$_product->getResource()->getAttribute('kitnekaa_offers')->getFrontend()->getValue($_product);
											$offer=$_product->getResource()->getAttribute('kitnekaa_offers')->getFrontend()->getValue($_product);
											$splitted=explode(' ',$offer);
											$first_word=$splitted[0];
											unset($splitted[0]);
											$remain=implode(' ',$splitted);
											?>
											<div class="prodPerOff">
												<div><span><?php echo $first_word ?></span> <?php echo $remain ?></div>
											</div>
										<?php }?>
									</div>
								</div>
								<div class="product-info col-lg-8 col-md-8 col-sm-7 col-xs-12">
									<div class="product-name">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
											<?php if( strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) > 100 ){
												echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 100);
											} else {
												echo $_helper->productAttribute($_product, $_product->getName(), 'name');
											}?>
										</a>
									</div>
									<!--<div class="product-review">
							<?php // echo $this->getReviewsSummaryHtml($_product, "short", true); ?>
                    	</div>-->

									<div class="product-sku-code">
										<?php echo "<strong>SKU Code:</strong> ".$_product->getSku()."</br>"; ?>
									</div>

									<div class="product-material-cut">
										<?php
										$attributes = Mage::getResourceModel('catalog/product_attribute_collection')
											->getItems();
										foreach ($attributes as $attribute){
											$label = $attribute->getFrontendLabel();
											if($label == 'Material To Cut'){
												$attcode = $attribute->getAttributecode();
												$value = $_product->getResource()->getAttribute($attcode)->getFrontend()->getValue($_product);
												if($value != ''){
													echo "<strong>Material To Cut:</strong> ".$value;
												}
											}
										}
										?>
									</div>
									<div class="kitnekaa-deals_text">
										<?php
										$kitnekaa_deals_text = $_product->getKitnekaaDealsText();
										$on_present = strpos($kitnekaa_deals_text,'On');
										if($on_present){
											$first = substr($kitnekaa_deals_text,0,strpos($kitnekaa_deals_text,'On'));
											$second = substr($kitnekaa_deals_text,strpos($kitnekaa_deals_text,'On'));
											echo $first." <span>".$second."</span>";
										}else{
											echo $kitnekaa_deals_text;
										}
										?>
									</div>
									<div class="product-price clearfix">
										<?php echo $this->getPriceHtml($_product, true) ?>
									</div>

									<?php
									// Provides extra blocks on which to hang some features for products in the list
									// Features providing UI elements targeting this block will display directly below the product name
									if ($this->getChild('name.after')) {
										$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
										foreach ($_nameAfterChildren as $_nameAfterChildName) {
											$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
											$_nameAfterChild->setProduct($_product);
											echo $_nameAfterChild->toHtml();
										}
									}
									?>

									<?php if($_product->getshort_description()) { ?>
										<!--<div class="product-desciption">
							<?php //echo $_product->getshort_description();?>
						</div>-->
									<?php } ?>

									<?php /* if($_product->isSaleable()): ?>
                                <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
                            <?php else: ?>
                                <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; */?>
									<div class="product-addto-wrap">
										<div class="product-addcart" style="display:none">
											<?php if($_product->isSaleable()): ?>
												<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
													<a  class="btn-cart iflogin"  title="<?php echo $this->__('Add to cart') ?>" href="javascript:void(0);" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" >
														<?php echo $this->__('Add to Cart') ?>
													</a>
												<?php } else { ?>
													<a id="ifloginatc<?php echo $_product->getId() ?>" class="btn-cart iflogin" style="display: none"  title="<?php echo $this->__('Add to cart') ?>" href="javascript:void(0);" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" >
														<?php echo $this->__('Add to Cart') ?>
													</a>


													<a class="btn-cart show-login-popup ifnotlogin" title="<?php echo $this->__('Add to cart') ?>" href="javascript:void(0);" data-id="ifloginatatc<?php echo $_product->getId() ?>">
														<?php echo $this->__('Add to Cart') ?>
													</a>
												<?php }?>

											<?php endif; ?>
										</div>
								<span class="getcode_outer">
									<?php $id =  $_product->getId();?>
									<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
										<span>
									<a onclick="setLocation('<?php echo $_product->getProductUrl() ?>?getQuote=1')" href="javascript:void(0);" class="getcode" ></a>
									</span>
									<?php } else { ?>
										<span class="iflogin" style="display: none">
									<a onclick="setLocation('<?php echo $_product->getProductUrl() ?>?getQuote=1')" href="javascript:void(0);" class="getcode"  id="iflogingc<?php echo $_product->getId() ?>"></a>
									</span>
										<span class="show-login-popup ifnotlogin" data-id="iflogingc<?php echo $_product->getId() ?>">
									<a href="javascript:void(0);" class="getcode" ></a>
									</span>
									<?php }?>

								</span>
										<div class="wishlist-compare">
											<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){

												if ( $this->helper('wishlist')->isAllow() ) : ?>
													<span  data-productid="<?php echo $_product->getId() ?>" data-productname="<?php echo $_product->getName() ?>" onclick="showSlPopup(event,jQuery(this))">
										<a class="link-wishlist" href="javascript:void(0)" title="<?php echo $this->__('Add to Shopping List') ?>">
											<?php echo $this->__('Add to Shopping List') ?>
										</a>
										</span>
												<?php endif; ?>
												<?php if( $_compareUrl=$this->getAddToCompareUrl($_product) ): ?>
													<a class="link-compare" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare'); ?>">
														<?php echo $this->__('Add to Compare') ?>
													</a>
												<?php endif;?>

											<?php } else { ?>

												<?php if ( $this->helper('wishlist')->isAllow() ) : ?>
													<span class="iflogin" style="display: none" data-productid="<?php echo $_product->getId() ?>" data-productname="<?php echo $_product->getName() ?>" onclick="showSlPopup(event,jQuery(this))"
														  id="iflogins<?php echo $_product->getId() ?>" >
										<a class="link-wishlist" href="javascript:void(0)" title="<?php echo $this->__('Add to Shopping List') ?>" >
											<?php echo $this->__('Add to Shopping List') ?>
										</a>
										</span>
													<span class="show-login-popup ifnotlogin" data-id="iflogins<?php echo $_product->getId() ?>">
										<a class="link-wishlist" href="javascript:void(0)" title="<?php echo $this->__('Add to Shopping List') ?>">
											<?php echo $this->__('Add to Shopping List') ?>
										</a>
										</span>
												<?php endif; ?>
												<?php if( $_compareUrl=$this->getAddToCompareUrl($_product) ): ?>
													<span class="iflogin" style="display: none" >
										<a class="link-compare" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare'); ?>" id="ifloginc<?php echo $_product->getId() ?>">
											<?php echo $this->__('Add to Compare') ?>
										</a>
										</span>
													<span class="show-login-popup ifnotlogin" data-id="ifloginc<?php echo $_product->getId() ?>">
										<a class="link-compare" href="javascript:void(0)" title="<?php echo $this->__('Add to Compare'); ?>" >
											<?php echo $this->__('Add to Compare') ?>
										</a>
										</span>
												<?php endif;?>

											<?php } ?>
										</div>
									</div>
								</div>
							</div>
						</li>
					<?php endforeach; ?>
				</ol>
				<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

			<?php else: ?>
			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $this->getColumnCount();?>
			<?php $i=0; foreach ($_productCollection as $_product):?>
			<?php
			$now = date("Y-m-d H:m:s");
			$newsFrom= $_product->getNewsFromDate();
			$newsTo=  $_product->getNewsToDate();
			$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
			$price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice();
			$special_from_date = $_product->getSpecialFromDate();
			$special_to_date = $_product->getSpecialToDate();
			?>
			<?php if ( $i++ == 0 ){ ?>
				<div class="products-grid">
				<div class="row">
			<?php } ?>
				<div class="item col-lg-4 col-md-4 col-sm-6 col-xs-12">
					<div class="item-inner">

						<div class="product-image">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
								<img id="product-collection-image-<?php echo $_product->getId(); ?>"
									 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,300); ?>"
									 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							</a>

							<?php
							// Provides extra blocks on which to hang some features for products in the list
							// Features providing UI elements targeting this block will display directly below the product name
							if ($this->getChild('name.after')) {
								$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
								foreach ($_nameAfterChildren as $_nameAfterChildName) {
									$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
									$_nameAfterChild->setProduct($_product);
									echo $_nameAfterChild->toHtml();
								}
							}

							//Mage::helper('users')->printPre(Mage::helper('udprod')->getProductVendor($_product)->getVendorName());
							?>

							<?php if ( $now>=$newsFrom && $now<=$newsTo ){ ?>
							<span class="new-product have-ico"><?php echo $this->__('New'); ?></span>
							<?php }
							/* if ( $specialprice ){ */?><!--
								<span class="sale-product have-ico"><?php /*echo $this->__('Sale'); */?></span>
							--><?php /*} */?>

							<?php if($_product->getKitnekaaOffers()){ ?>
								<?php
								$offer=$_product->getResource()->getAttribute('kitnekaa_offers')->getFrontend()->getValue($_product);
								$splitted=explode(' ',$offer);
								$first_word=$splitted[0];
								unset($splitted[0]);
								$remain=implode(' ',$splitted);
								?>
								<div class="prodPerOff">
									<div><span><?php echo $first_word ?></span> <?php echo $remain ?></div>
								</div>
							<?php }?>
						</div>

						<div class="product-info">
							<div class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
									<?php if( strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) > 100 ){
										echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 100);
									} else {
										echo $_helper->productAttribute($_product, $_product->getName(), 'name');
									}?>
								</a>
							</div>
							<div class="product-sku-code">
								<?php echo "<strong>SKU Code:</strong> ".$_product->getSku()."</br>"; ?>
							</div>

							<?php
							$attributes = Mage::getResourceModel('catalog/product_attribute_collection')
								->getItems();
							foreach ($attributes as $attribute){
								$label = $attribute->getFrontendLabel();
								if($label == 'Material To Cut'){
									$attcode = $attribute->getAttributecode();
									$value = $_product->getResource()->getAttribute($attcode)->getFrontend()->getValue($_product);
									if($value != ''){
										echo "<div class='product-material-cut' title='".$value."'><strong>Material To Cut:</strong> ".$value."</div>";
									}
								}
							}
							?>
							<!--<div class="kitnekaa-deals_text">
								<?php
							/*									$kitnekaa_deals_text = $_product->getKitnekaaDealsText();
                                                                $on_present = strpos($kitnekaa_deals_text,'On');
                                                                if($on_present){
                                                                    $first = substr($kitnekaa_deals_text,0,strpos($kitnekaa_deals_text,'On'));
                                                                    $second = substr($kitnekaa_deals_text,strpos($kitnekaa_deals_text,'On'));
                                                                    echo $first." <span>".$second."</span>";
                                                                }else{
                                                                  echo $kitnekaa_deals_text;
                                                                }
                                                            */?>
							</div>-->
							<!--<div class="product-review">
								<?php //echo $this->getReviewsSummaryHtml($_product, "short", true); ?>
							</div>-->
							<div class="product-price">
								<?php echo $this->getPriceHtml($_product, true) ?>
								<div class="wishlist-compare">
									<?php

									if(Mage::getSingleton('customer/session')->isLoggedIn()){

										if ( $this->helper('wishlist')->isAllow() ) : ?>
											<span  data-productid="<?php echo $_product->getId() ?>" data-productname="<?php echo $_product->getName() ?>" onclick="showSlPopup(event,jQuery(this))">
										<a class="link-wishlist" href="javascript:void(0)" title="<?php echo $this->__('Add to Shopping List') ?>">
											<?php echo $this->__('Add to Shopping List') ?>
										</a>
										</span>
										<?php endif; ?>
										<?php if( $_compareUrl=$this->getAddToCompareUrl($_product) ): ?>
											<a class="link-compare" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare'); ?>">
												<?php echo $this->__('Add to Compare') ?>
											</a>
										<?php endif;?>

									<?php }else{ ?>

										<?php if ( $this->helper('wishlist')->isAllow() ) : ?>
											<span class="iflogin" style="display: none" data-productid="<?php echo $_product->getId() ?>" data-productname="<?php echo $_product->getName() ?>" onclick="showSlPopup(event,jQuery(this))"
												  id="iflogins<?php echo $_product->getId() ?>" >
										<a class="link-wishlist" href="javascript:void(0)" title="<?php echo $this->__('Add to Shopping List') ?>" >
											<?php echo $this->__('Add to Shopping List') ?>
										</a>
										</span>
											<span class="show-login-popup ifnotlogin" data-id="iflogins<?php echo $_product->getId() ?>">
										<a class="link-wishlist" href="javascript:void(0)" title="<?php echo $this->__('Add to Shopping List') ?>">
											<?php echo $this->__('Add to Shopping List') ?>
										</a>
										</span>
										<?php endif; ?>
										<?php if( $_compareUrl=$this->getAddToCompareUrl($_product) ): ?>
											<span class="iflogin" style="display: none" >
										<a class="link-compare" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare'); ?>" id="ifloginc<?php echo $_product->getId() ?>">
											<?php echo $this->__('Add to Compare') ?>
										</a>
										</span>
											<span class="show-login-popup ifnotlogin" data-id="ifloginc<?php echo $_product->getId() ?>">
										<a class="link-compare" href="javascript:void(0)" title="<?php echo $this->__('Add to Compare'); ?>" data-href="<?php echo $_compareUrl ?>">
											<?php echo $this->__('Add to Compare') ?>
										</a>
										</span>
										<?php endif;?>

									<?php } ?>
								</div>
							</div>

							<div class="product-addto-wrap">
								<div class="product-addcart" style="display:none">
									<?php if($_product->isSaleable()): ?>
										<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
											<a  class="btn-cart iflogin"  title="<?php echo $this->__('Add to cart') ?>" href="javascript:void(0);" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" >
												<?php echo $this->__('Add to Cart') ?>
											</a>
										<?php } else { ?>
											<a id="ifloginatc<?php echo $_product->getId() ?>" class="btn-cart iflogin" style="display: none"  title="<?php echo $this->__('Add to cart') ?>" href="javascript:void(0);" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" >
												<?php echo $this->__('Add to Cart') ?>
											</a>


											<a class="btn-cart show-login-popup ifnotlogin" title="<?php echo $this->__('Add to cart') ?>" href="javascript:void(0);" data-id="ifloginatatc<?php echo $_product->getId() ?>">
												<?php echo $this->__('Add to Cart') ?>
											</a>
										<?php }?>
									<?php else: ?>
										<p class="availability out-of-stock">
											<span><?php echo $this->__('Out of stock') ?> </span>
										</p>
									<?php endif; ?>
								</div>
								<?php $id =  $_product->getId(); ?>
								<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
									<span>
									<a onclick="setLocation('<?php echo $_product->getProductUrl() ?>?getQuote=1')" href="javascript:void(0);" class="getcode" ></a>
									</span>
								<?php } else { ?>
									<span class="iflogin" style="display: none">
									<a onclick="setLocation('<?php echo $_product->getProductUrl() ?>?getQuote=1')" href="javascript:void(0);" class="getcode"  id="iflogingc<?php echo $_product->getId() ?>"></a>
									</span>
									<span class="show-login-popup ifnotlogin" data-id="iflogingc<?php echo $_product->getId() ?>">
									<a href="javascript:void(0);" class="getcode" ></a>
									</span>
								<?php }?>
							</div>
						</div>
					</div>
				</div>
				<?php if ( $i == $_collectionSize ){ ?>
				</div>
				</div>
			<?php } ?>
			<?php endforeach ?>
				<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
			<?php endif; ?>
		</div>

		<div class="toolbar-bottom">
			<?php echo $this->getToolbarHtml() ?>
		</div>

	</div>
	<?php if (!$this->getRequest()->isAjax()): ?>
		</div>
	<?php endif; ?>
<?php endif; ?>
<?php
echo Mage::app()->getLayout()->createBlock('core/template')->setTemplate('persistent/customer/form/kit_min_login.phtml')->toHtml();
?>
<?php
echo Mage::app()->getLayout()->createBlock('shoppinglist/index')->setTemplate('shoppinglist/min_shopping_list.phtml')->toHtml();
?>
<?php if ($this->helper('sm_shopby')->isAjaxEnabled() && !$this->getRequest()->isAjax()): ?>
	<script type="text/javascript">
		//<![CDATA[
		function pushState(data, link, replace) {
			var History = window.History;
			if ( !History.enabled ) {
				return false;
			}

			if (replace) {
				History.replaceState(data, document.title, link);
			} else {
				History.pushState(data, document.title, link);
			}
		}

		function handleEvent(el, event) {
			var url, fullUrl;
			if (typeof el === 'string') {
				url = el;
			} else if (el.tagName.toLowerCase() === 'a') {
				url = $(el).readAttribute('href');
			} else if (el.tagName.toLowerCase() === 'select') {
				url = $(el).getValue();
			}

			<?php // Add this to query string for full page caching systems ?>
			if (url.indexOf('?') != -1) {
				fullUrl = url + '&isLayerAjax=1';
			} else {
				fullUrl = url + '?isLayerAjax=1';
			}

			$('loading').show();
			$('ajax-errors').hide();

			pushState(null, url, false);

			new Ajax.Request(fullUrl, {
				method: 'get',
				onSuccess: function(transport) {
					if (transport.responseJSON) {
						$('catalog-listing').update(transport.responseJSON.listing);
						$('layered-navigation').update(transport.responseJSON.layer);
						pushState({
							listing: transport.responseJSON.listing,
							layer: transport.responseJSON.layer
						}, url, true);
						ajaxListener();
					} else {
						$('ajax-errors').show();
					}
					$('loading').hide();
				}
			});

			if (event) {
				event.preventDefault();
			}
		}
		function ajaxListener() {
			var els;
			els = $$('div.pager-wrapper a').concat(
				$$('div.sort-by-wrap a'),
				$$('div.view-mode-wrap a'),
				// $$('div.pager select'),
				$$('div.sorter select'),
				$$('div.block-layered-nav a')
			);
			els.each(function(el) {
				if (el.tagName.toLowerCase() === 'a') {
					$(el).observe('click', function(event) {
						handleEvent(this, event);
					});
				} else if (el.tagName.toLowerCase() === 'select') {
					$(el).setAttribute('onchange', '');
					$(el).observe('change', function(event) {
						handleEvent(this, event);
					});
				}
			});
		}
		document.observe("dom:loaded", function() {
			ajaxListener();

			(function(History) {
				if ( !History.enabled ) {
					return false;
				}

				pushState({
					listing: $('catalog-listing').innerHTML,
					layer: $('layered-navigation').innerHTML
				}, document.location.href, true);

				// Bind to StateChange Event
				History.Adapter.bind(window, 'popstate', function(event) {
					if (event.type == 'popstate') {
						var State = History.getState();
						$('catalog-listing').update(State.data.listing);
						$('layered-navigation').update(State.data.layer);
						ajaxListener();
					}
				});
			})(window.History);
		});
		//]]>
	</script>
<?php endif; ?>

<?php if ($this->getRequest()->isAjax()){ ?>


<?php } ?>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
	$_afterChildren = $this->getChild('after')->getSortedChildren();
	foreach ($_afterChildren as $_afterChildName) {
		$_afterChild = $this->getChild('after')->getChild($_afterChildName);
		//set product collection on after blocks
		$_afterChild->setProductCollection($_productCollection);
		echo $_afterChild->toHtml();
	}
}
?>

<script>
	jQuery( document ).ready(function($) {
		$(".products-grid .product-name").dotdotdot({
			height:38
		});
		$(".products-grid .product-material-cut").dotdotdot({
			height:34
		});

		function calCateHeight(){
			var mainCateHeight = $('#yt_header_left').height();
			$('.sm_megamenu_dropdown_1column ').css({'min-height':mainCateHeight})
		};

		$(window).load(function(){
			calCateHeight();
		});

		$('.sambar ul li').hover(function(){
			setTimeout(function(){
				var mainCateHeight = $('.sm_megamenu_wrapper_vertical_menu').height();
				$('.sm_megamenu_dropdown_1column ').css({'min-height':mainCateHeight})
			},500)
		});


		$("#narrow-by-list ol li a").click(function() {
			$(this).toggleClass('checked');
		});

		//Side Category Filter
		var sideCateParent = $('.narrow-by-list'),
			FilterList = $('#narrow-by-list ol .filter_list');
		FilterList.each(function(){
			var thisList = $(this);
			thisList.children('li').hide().filter(':lt(4)').show();
		});

		FilterList.find('.morefilter').on('click',function(){
			$(this).siblings(':gt(3)').slideToggle();
			if($(this).text() == 'Less'){
				$(this).html('More')
			}else if($(this).text() == 'More'){
				$(this).html('Less')
			}
		});

		var filterListHeight = $('.filter_list li').height();
		//Expand Function
		$.fn.clickToggle = function(func1, func2) {
			var funcs = [func1, func2];
			this.data('toggleclicked', 0);
			this.click(function() {
				var data = $(this).data();
				var tc = data.toggleclicked;
				$.proxy(funcs[tc], this)();
				data.toggleclicked = (tc + 1) % 2;
			});
			return this;
		};

		$('.expandfilter').clickToggle(function() {
			$(this).parent('ol').find('.filter_list').stop().slideUp();
			$(this).addClass('expand-active');
		}, function() {
			$(this).parent('ol').find('.filter_list li').show();
			$(this).parent('ol').find('.filter_list .morefilter').html('Less')
			$(this).parent('ol').find('.filter_list').stop().slideDown();
			$(this).removeClass('expand-active');
		});

		$(window).resize(function(){
			var winWidth = $(window).width(),
				banimgHeight = $('#slider1 > img').height();

			//if(winWidth <= 767){
			$('#slider1').css({'height':banimgHeight})
			//}
		});

		var sliderinterval;
		sliderinterval = setInterval(slidemoveFun, 3000);

		function slidemoveFun(){
			$('#next').trigger('click');
		}

		//get new arrival offset position
		//var newarrivalPosition = $('.yt-tab-listing.first-load').offset().top;

		$(window).load(function(){
			$('#thumb li').click(function(){
				clearInterval(sliderinterval );
				sliderinterval = setInterval(slidemoveFun, 3000)
			});

			$('#thumb li:last').click(function(){
				//$('body,html').animate({scrollTop: newarrivalPosition}, 1000);
			});
		});

	});
</script>