<?php
$items = $this->getItems();
/**
 * @var $this Cminds_MultiUserAccounts_Block_Wihslist
 */
?>
<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('Create New Pick List') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getUrl("*/*/save") ?>" method="post" id="form-validate">
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey') ?>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="name" class="required"><em>*</em><?php echo $this->__('Pick List Name') ?>
                        </label>

                        <div class="input-box">
                            <input type="text" name="name" id="name"
                                   value=""
                                   title="<?php echo $this->__('Name') ?>" maxlength="128"
                                   class="input-text required-entry"/>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Save') ?>" class="button">
                <span><span><?php echo $this->__('Save') ?></span></span>
            </button>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        //]]>
    </script>
</div>
