<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<?php
foreach ($this->getAttributeCodes() as $_attributeCode) {
    ?>
    <li class="fields amar-profile">
    <?php echo $this->getAttributeFrontendHtmlControl($_attributeCode); ?>
    </li>
        <?php
    }
    ?>

<script type="text/javascript">
    document.observe("dom:loaded",function(){
        var amarProfileLis = $$('li.amar-profile'); 
        
        amarProfileLis.each(function(el,ind){
            var liElement = new Element("li");
            liElement.addClassName("fields");
            liElement.innerHTML = el.innerHTML;
                  
            if($$("li.control").length > 0)
            {
                $$("li.control").each(function(e,i){
                    if((e.down("input",0).readAttribute("id") == 'is_subscribed') && (i == 0))
                    {
                        e.insert({"before":liElement});
                    }
                });
            }
            else
            {
                ulElement.insert({"bottom":liElement});
            }
            el.remove();
        });
    });
</script>