<?php
/*------------------------------------------------------------------------
 # SM Mega Menu - Version 1.1
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<?php //if($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::HORIZONTAL): ?>

<!--link media="all" href="<?php //echo $this->getSkinUrl('sm/megamenu/css/horizontal/black/megamenu.css');?>" type="text/css" rel="stylesheet">

<?php //elseif($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::VERTICAL):	?>

<link media="all" href="<?php //echo $this->getSkinUrl('sm/megamenu/css/vertical/black/megamenu.css');?>" type="text/css" rel="stylesheet"-->
<?php //endif	?>