<script type="text/javascript">
    order.sidebarHide();
    Event.observe(window, 'load',  function() {
        if (window.productConfigure) {
            productConfigure.addListType('product_to_add', {
                urlFetch: '<?php echo $this->getUrl('*/adminhtml_quote_create/configureProductToAdd') ?>'
            });
            productConfigure.addListType('quote_items', {
                urlFetch: '<?php echo $this->getUrl('*/adminhtml_quote_create/configureQuoteItems') ?>'
            });
        }
    });
</script>
