<?php foreach ($this->getTotals() as $_code => $_total):?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else: ?>
        <tr class="<?php echo $_code ?>">
            <td <?php echo $this->getLabelProperties() ?>>
                <?php if ($_code == "grand_total"): ?>
                    <strong><?php echo $this->escapeHtml($_total->getTitle()); ?></strong>
                <?php else: ?>
                    <?php echo $this->escapeHtml($_total->getTitle()); ?>
                <?php endif ?>
            </td>
            <td <?php echo $this->getValueProperties() ?>>
                <?php if ($_code == "grand_total"): ?>
                    <strong><?php echo $this->formatValue($_total);
                    ?></strong>
                <?php else: ?>
                    <?php  echo $this->formatValue($_total) ?>
        <?php endif ?>
            </td>
        </tr>
    <?php endif ?>
<?php endforeach  ?>