<?php
/*------------------------------------------------------------------------
 # SM Deal - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>
		
<script type="text/javascript">
//<![CDATA[
data = new Date(2013,10,26,12,00,00);
var listdeal = [];
function CountDown(date,id){
	dateNow = new Date();
	amount = date.getTime() - dateNow.getTime();
	delete dateNow;
	if(amount < 0){
		document.getElementById(id).innerHTML="Now!";
	} else{
		days=0;hours=0;mins=0;secs=0;out="";
		amount = Math.floor(amount/1000);
		days=Math.floor(amount/86400);
		amount=amount%86400;
		hours=Math.floor(amount/3600);
		amount=amount%3600;
		mins=Math.floor(amount/60);
		amount=amount%60;
		secs=Math.floor(amount);
		if(days != 0){out += "<div class='time-item time-day'>" + "<div class='num-time'>" + days + "</div>" +" <div class='name-time'>"+((days==1)?"Day":"Days") + "</div>"+"</div> ";}
		if(hours != 0){out += "<div class='time-item time-hour'>" + "<div class='num-time'>" + hours + "</div>" +" <div class='name-time'>"+((hours==1)?"Hour":"Hours") + "</div>"+"</div> ";}
		out += "<div class='time-item time-min'>" + "<div class='num-time'>" + mins + "</div>" +" <div class='name-time'>"+((mins==1)?"Min":"Mins") + "</div>"+"</div> ";
		out += "<div class='time-item time-sec'>" + "<div class='num-time'>" + secs + "</div>" +" <div class='name-time'>"+((secs==1)?"Sec":"Secs") + "</div>"+"</div> ";
		out = out.substr(0,out.length-2);
		document.getElementById(id).innerHTML=out;
		setTimeout(function(){CountDown(date,id)}, 1000);
	}
}
//]]>
</script>
<?php
$dayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
$deals  = Mage::getResourceModel('deal/deal_product_collection')->joinFields()->joinFieldsdeal()
				->addFilter('status', '1', "=")
				->addFilter('end_date', $dayDate, ">");

if(Mage::getStoreConfig('deal/deal/orderby') == 1){
	$deals->OrderbyAdd('start_date','desc');
}else{
	$deals->OrderbyAdd('end_date','desc');
}
		
$productBlock=$this->getLayout()->createBlock("catalog/product_list");
$check_array =$deals->getData();

/*get config backend*/
$general_setting = Mage::getStoreConfig('deal/deal');
$product_setting = Mage::getStoreConfig('deal/product_display_setting');
?>
<?php if( !empty($check_array) && $general_setting['isenabled'] == 1 ){
	$uniqued ='sm_deal_'.rand().time();
?>
<div id="<?php echo $uniqued;?>" class="sm-deal-wrap">
	<div class="sm-deal-inner">
		<div class="sm-deal-title">
			<span><?php echo $general_setting['title'] ?></span>			
		</div>
		<div class="deal-list-item">
			<?php $j = 0; foreach($deals->getData() as $product_data){ 
			$_product = Mage::getModel('catalog/product')->load($product_data['entity_id']); ?>
			<div class="item-deal">
				<div class="item-wrap">
					<?php if( $product_setting['product_title_disp'] == 1 ){?>
					<div class="item-title">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo substr($this->htmlEscape($_product->getName()), 0, $product_setting['product_title_max_characters']);						
						?>
						</a>
					</div>
					<?php }?>
					<?php if( $product_setting['product_reviews_count'] == 1 ){?>
					<div class="item-review">
						<?php  echo $productBlock->getReviewsSummaryHtml($_product, false, true); ?>
					</div>
					<?php }?>	
					<?php if( $product_setting['product_price_disp'] == 1 ){?>
					<div class="item-price">
						<?php if($_product->isSaleable()){
							echo $productBlock->getPriceHtml($_product, true); 
						} ?>
					</div>	
					<?php }?>						
					<div class="item-image">
						<a  href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">											
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($product_setting['product_image_width'],$product_setting['product_image_height']); ?>"/>
						</a>	
					</div>
					
					<?php if( $product_setting['product_description_disp'] == 1 ){?>
					<div class="item-des">
						<?php echo substr($_product->getshort_description(), 0, $product_setting['product_description_max_characters']);?>
					</div>
					<?php }?>
										
					<?php if($_product->getIsSalable()): ?>
						<button class="button btn-cart" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
						<?php else: ?>
						<div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
					<?php endif; ?>
					<div class="product-wishlist">
						<?php if ( $this->helper('wishlist')->isAllow() ) : ?>
						<a class="link-wishlist" href="<?php echo Mage::helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>">
							<?php echo $this->__('Add to Wishlist') ?>
						</a>
						<?php endif; ?>
					</div>
					<?php if( $_compareUrl= $productBlock->getAddToCompareUrl($_product) ): ?>
					<div class="product-compare">
						<a class="link-compare" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare'); ?>">
							<?php echo $this->__('Add to Compare') ?>
						</a>
					</div>
					<?php endif;?>
					<div class="product-timer-wrap">	
						<div id="product_time_<?php echo $j;?>"></div>
					</div>	
					<script type="text/javascript">
					//<![CDATA[
						listdeal.push('product_time_<?php echo $j."&&||&&".date("Y/m/d", strtotime($product_data['end_date']));?>') ;
					//]]>
					</script>											
				</div>
			</div>
			<?php $j++; }?>			
		</div>				
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
window.onload=function(){
	if(listdeal.length > 0){
		for(i=0;i<listdeal.length;i++)
		{
			var arr = listdeal[i].split("&&||&&"); 
			var data = new Date(arr[1]);
			CountDown(data, arr[0]);
		}	
	}
};
//]]>
</script>	
<?php } ?>

