<?php
/**
 * @category   Taxcation
 * @package    Nest_Taxcation
 */
?>

<?php $this->setPriceDataObject($this->getSource()) ?>

<?php if ((float) $this->getSource()->getNestTaxTotalAmount()): ?>
    <tr>
        <!-- <td class="label"><?php echo Mage::helper('taxcation')->__('Taxcation') ?></td> -->
        <td class="label"><?php echo $this->getSource()->getNestTaxName() ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getNestTaxTotalAmount(), $this->getSource()->getNestTaxTotalAmount()); ?>
        </td>
    </tr>
<?php endif; ?>