var ConfigurableMediaImages={imageType:null,productImages:{},imageObjects:{},arrayIntersect:function(a,b){var ai=0,bi=0;var result=new Array();while(ai<a.length&&bi<b.length)
{if(a[ai]<b[bi]){ai++;}
else if(a[ai]>b[bi]){bi++;}
else
{result.push(a[ai]);ai++;bi++;}}
return result;},getCompatibleProductImages:function(productFallback,selectedLabels){var compatibleProducts=[];var compatibleProductSets=[];selectedLabels.each(function(selectedLabel){if(!productFallback['option_labels'][selectedLabel]){return;}
var optionProducts=productFallback['option_labels'][selectedLabel]['products'];compatibleProductSets.push(optionProducts);optionProducts.each(function(productId){compatibleProducts.push(productId);});});compatibleProductSets.each(function(productSet){compatibleProducts=ConfigurableMediaImages.arrayIntersect(compatibleProducts,productSet);});return compatibleProducts;},isValidImage:function(fallbackImageUrl){if(!fallbackImageUrl){return false;}
return true;},getSwatchImage:function(productId,optionLabel,selectedLabels){var fallback=ConfigurableMediaImages.productImages[productId];if(!fallback){return null;}
var currentLabelImage=fallback['option_labels'][optionLabel];if(currentLabelImage&&fallback['option_labels'][optionLabel]['configurable_product'][ConfigurableMediaImages.imageType]){return fallback['option_labels'][optionLabel]['configurable_product'][ConfigurableMediaImages.imageType];}
var compatibleProducts=ConfigurableMediaImages.getCompatibleProductImages(fallback,selectedLabels);if(compatibleProducts.length==0){return null;}
$j.each(fallback['option_labels'],function(key,value){var image=value['configurable_product'][ConfigurableMediaImages.imageType];var products=value['products'];if(image){var isCompatibleProduct=ConfigurableMediaImages.arrayIntersect(products,compatibleProducts).length>0;if(isCompatibleProduct){return image;}}});var childSwatchImage=null;var childProductImages=fallback[ConfigurableMediaImages.imageType];compatibleProducts.each(function(productId){if(childProductImages[productId]&&ConfigurableMediaImages.isValidImage(childProductImages[productId])){childSwatchImage=childProductImages[productId];return false;}});if(childSwatchImage){return childSwatchImage;}
if(childProductImages[productId]&&ConfigurableMediaImages.isValidImage(childProductImages[productId])){return childProductImages[productId];}
return null;},getImageObject:function(productId,imageUrl){var key=productId+'-'+imageUrl;if(!ConfigurableMediaImages.imageObjects[key]){var image=$j('<img />');image.attr('src',imageUrl);ConfigurableMediaImages.imageObjects[key]=image;}
return ConfigurableMediaImages.imageObjects[key];},updateImage:function(el){var select=$j(el);var label=select.find('option:selected').attr('data-label');var productId=optionsPrice.productId;var selectedLabels=new Array();$j('.product-options .super-attribute-select').each(function(){var $option=$j(this);if($option.val()!=''){selectedLabels.push($option.find('option:selected').attr('data-label'));}});var swatchImageUrl=ConfigurableMediaImages.getSwatchImage(productId,label,selectedLabels);if(!ConfigurableMediaImages.isValidImage(swatchImageUrl)){return;}
var swatchImage=ConfigurableMediaImages.getImageObject(productId,swatchImageUrl);ProductMediaManager.swapImage(swatchImage);},wireOptions:function(){$j('.product-options .super-attribute-select').change(function(e){ConfigurableMediaImages.updateImage(this);});},swapListImage:function(productId,imageObject){var originalImage=$j('#product-collection-image-'+productId);if(imageObject[0].complete){originalImage.addClass('hidden');$j('.product-collection-image-'+productId).remove();imageObject.insertAfter(originalImage);}else{var wrapper=originalImage.parent();wrapper.addClass('loading');imagesLoaded(imageObject,function(){wrapper.removeClass('loading');originalImage.addClass('hidden');$j('.product-collection-image-'+productId).remove();imageObject.insertAfter(originalImage);});}},swapListImageByOption:function(productId,optionLabel){var swatchImageUrl=ConfigurableMediaImages.getSwatchImage(productId,optionLabel,[optionLabel]);if(!swatchImageUrl){return;}
var newImage=ConfigurableMediaImages.getImageObject(productId,swatchImageUrl);newImage.addClass('product-collection-image-'+productId);ConfigurableMediaImages.swapListImage(productId,newImage);},setImageFallback:function(productId,imageFallback){ConfigurableMediaImages.productImages[productId]=imageFallback;},init:function(imageType){ConfigurableMediaImages.imageType=imageType;ConfigurableMediaImages.wireOptions();}};