<?php
$efConfig = Mage::helper('udprod')->getQuickCreateFieldsConfig();
$_yesnoOpts = Mage::getSingleton('udropship/source')->setPath('yesno')->toOptionHash();
?>

<div class="grid">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:70px">
        <col width="150" />
        <col width="70" />
        <col width="70" />
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('udropship')->__('Field') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Sort Order') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Action') ?></th>
            </tr>
            <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
                <td>
                    <select name="<?php echo $this->getFieldName()?>[$ROW][column_field]">
                    <option value=""><?php echo Mage::helper('udropship')->__('* Please select')?></option>
                    <?php if (is_array($efConfig)): foreach ($efConfig as $efc): ?>
                        <optgroup label="<?php echo $this->htmlEscape($efc['label'])?>">
                        <?php if (is_array($efc['values'])): foreach ($efc['values'] as $fId=>$fLbl): ?>
                        <option alt="column_field" value="<?php echo $fId?>"><?php echo $this->htmlEscape($fLbl)?></option>
                        <?php endforeach; endif; ?>
                        </optgroup>
                    <?php endforeach; endif; ?>
                    </select>
                    <br />
                    <span><?php echo Mage::helper('udropship')->__('Is Required')?></span>
                    <input alt="is_required" value="1" name="<?php echo $this->getFieldName()?>[$ROW][is_required]" style="width:20px" type="checkbox" />
                </td>
                <td>
                    <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][sort_order]" value="$SORT_ORDER" style="width:70px" />
                </td>
                <td>
                    <button type="button" class="scalable delete"><span></span></button>
                </td>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th colspan="4" class="a-left">
                    <div class="left"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span><?php echo Mage::helper('udropship')->__('Add Field') ?></span></button></div>
                </th>
            </tr>
        </tfoot>
        <tbody>
        </tbody>
    </table>

</div>

<style type="text/css">
</style>

<script type="text/javascript">
//<![CDATA[
(function ()
{
    var lastRowNum = 0;
    var tbody = $$('#<?php echo $this->suffixId('cfgTable')?> tbody')[0]
    var suffixIdTpl = new Template('<?php echo $this->suffixId('#{key}') ?>')

    var udpAddRow = function (inData)
    {
        var rowHtml = $('<?php echo $this->suffixId('rowTpl')?>').innerHTML
        var data = {
            is_required: '0',
            sort_order: '0',
        }
        Object.extend(data, inData);
        data.row = ++lastRowNum;

        var isIE = (/msie [1-8]\./i).test(navigator.userAgent);
        var numericVars = ['sort_order', 'is_required'];
        var forcedNumericVars = [];
        var keys = $H(data).keys().sortBy(function(s){return (''+s).length}).reverse();
        for (j=0; j<keys.length; j++) {
            var i=keys[j];
            value = data[i] || ''
            if (-1 != numericVars.indexOf(i) && data[i]
                || -1 != forcedNumericVars.indexOf(i)
            ) {
                value *= 1;
                data[i] = value;
            }
            if (i!=='row' && isIE) value = '"'+value+'"';
            rowHtml = rowHtml.replace(new RegExp('\\$'+i.toUpperCase(), 'g'), value);
        }
        var regExTpl = [
            new Template('<option (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>]))){2})'),
            new Template('<option $1 selected="selected"'),
            new Template('<input (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>])|type="?checkbox"?)){3})'),
            new Template('<input $1 checked="checked"')
        ];
        var selectFields = $H({column_field: 0, is_required: 0});
        selectFields.each(function(pair){
            var varsForEval, value=data[pair.key], key=pair.key;
            for (var rxIdx=0; rxIdx<regExTpl.length; rxIdx+=2) {
                varsForEval = [];
                if (value) {
                    if (!Object.isArray(value)) {
                        value = String.interpret(value).split(',');
                    }
                    value.each(function(val){
                        varsForEval.push({key: key, value: val});
                    })
                } else {
                    varsForEval.push({key: key, value: value});
                }
                for (var vfeIdx=0; vfeIdx<varsForEval.length; vfeIdx++) {
                    var varForEval = varsForEval[vfeIdx];
                    var rxFind = regExTpl[rxIdx].evaluate(varForEval);
                    var rxReplace = regExTpl[rxIdx+1].evaluate(varForEval);
                    rowHtml = rowHtml.replace(new RegExp(rxFind, 'i'), rxReplace);
                }
            }
        });
        tbody.insert('<tr>'+rowHtml+'</tr>')
        var trs = tbody.childElements()
        var tr = trs[trs.length-1]
        tr.addClassName(lastRowNum%2 ? 'odd' : 'even')

        var toggleFields = [];
        toggleFields.each(function(key){
            var yesKey = suffixIdTpl.evaluate({key: 'yes__'+key+'_'+data.row});
            var noKey = suffixIdTpl.evaluate({key: 'no__'+key+'_'+data.row});
            if (!data[key]) {
                $$('.'+yesKey).invoke('hide');
                $$('.'+noKey).invoke('show');
            } else {
                $$('.'+yesKey).invoke('show');
                $$('.'+noKey).invoke('hide');
            }
        });

        var del = $(tr).select('button.delete')[0];
        if (del) {
            $(del).observe('click', function(e) { e.stop(); $(del.parentNode.parentNode).remove() })
        }
    }

    $('<?php echo $this->suffixId('addBtn')?>').observe('click', function(e) { e.stop(); udpAddRow() });
    window['<?php echo $this->suffixId('addBtn')?>udpAddRow'] = udpAddRow;

})();
//]]>
</script>



