<?php
$_tsHlp = Mage::helper('udtiership');
$_element = $this->getElement();
$this->setFieldName($_element->getName());
$fValue = $_element->getValue();
$cShipClass = Mage::getSingleton('udshipclass/source')->setPath('customer_ship_class')->toOptionHash();
$deliveryTypes = Mage::getResourceModel('udtiership/deliveryType_collection')->toOptionHash();
$customerGroupIds = $_tsHlp->getCustomerGroups();
$useCustomerGroup = Mage::getStoreConfigFlag('carriers/udtiership/use_customer_group');
$store = Mage::app()->getDefaultStoreView();
$columnsCount = 5 + (int)$this->isShowAdditionalColumn() + (int)$this->isShowHandlingColumn();
?>

<tr>
    <td class="label"><?php echo trim($_element->getLabelHtml()) ?></td>
    <td class="grid" colspan=10>

    <input id="<?php echo $_element->getHtmlId()?>" type="hidden" />
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:550px">
        <col width="150" />
        <col width="150" />
        <col width="100" />
        <?php if ($this->isShowAdditionalColumn()): ?>
            <col width="100" />
        <?php endif ?>
        <?php if ($this->isShowHandlingColumn()): ?>
            <col width="100" />
        <?php endif ?>
        <col width="50" />
        <col width="50" />
        <thead>
        <tr class="headings">
            <th><?php echo Mage::helper('udropship')->__('Delivery Type') ?></th>
            <th><?php echo Mage::helper('udropship')->__('Customer') ?></th>
            <th><?php echo Mage::helper('udropship')->__('Cost for the first item') ?></th>
            <?php if ($this->isShowAdditionalColumn()): ?>
            <th><?php echo Mage::helper('udropship')->__('Additional item cost') ?></th>
            <?php endif ?>
            <?php if ($this->isShowHandlingColumn()): ?>
            <th><?php echo Mage::helper('udropship')->__('Tier handling fee') ?></th>
            <?php endif ?>
            <th><?php echo Mage::helper('udropship')->__('Sort Order') ?></th>
            <th><?php echo Mage::helper('udropship')->__('Action') ?></th>
        </tr>
        <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
            <td>
                <select name="<?php echo $this->getFieldName()?>[$ROW][delivery_type_id]" style="width:150px">
                    <?php foreach ($deliveryTypes as $dtId=>$dtLabel): ?>
                        <option alt="delivery_type_id" value="<?php echo $dtId?>"><?php echo $this->htmlEscape($dtLabel)?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td>
                <select multiple="multiple" name="<?php echo $this->getFieldName()?>[$ROW][customer_shipclass_id][]" style="width:150px; height: 150px">
                    <option alt="customer_shipclass_id" value="*"><?php echo Mage::helper('udropship')->__('*** All ***')?></option>
                    <?php foreach ($cShipClass as $cscId=>$cscLabel): ?>
                        <option alt="customer_shipclass_id" value="<?php echo $cscId?>"><?php echo $this->htmlEscape($cscLabel)?></option>
                    <?php endforeach; ?>
                </select>
                <?php if ($useCustomerGroup): ?>
                    <h4><?php echo Mage::helper('udropship')->__('Custmer Group')?></h4>
                    <select multiple="multiple" name="<?php echo $this->getFieldName()?>[$ROW][customer_group_id][]" style="width:150px; height: 150px">
                        <option alt="customer_group_id" value="*"><?php echo Mage::helper('udropship')->__('*** All ***')?></option>
                        <?php foreach ($customerGroupIds as $cscId=>$cscLabel): ?>
                            <option alt="customer_group_id" value="<?php echo $cscId?>"><?php echo $this->htmlEscape($cscLabel)?></option>
                        <?php endforeach; ?>
                    </select>
                <?php else: ?>
                    <input type="hidden" name="<?php echo $this->getFieldName()?>[$ROW][customer_group_id][]" value="*" />
                <?php endif ?>
            </td>
            <td>
                <input name="<?php echo $this->getFieldName()?>[$ROW][cost]" class="input-text" type="text"  value="$COST" style="width: 100px" />
                <br /><strong>[<?php echo $this->getSuffix('cost', true) ?>]</strong>
            </td>
            <?php if ($this->isShowAdditionalColumn()): ?>
            <td>
                <input name="<?php echo $this->getFieldName()?>[$ROW][additional]" class="input-text" type="text"  value="$ADDITIONAL" style="width: 100px" />
                <br /><strong>[<?php echo $this->getSuffix('additional', true) ?>]</strong>
            </td>
            <?php endif ?>
            <?php if ($this->isShowHandlingColumn()): ?>
            <td>
                <input name="<?php echo $this->getFieldName()?>[$ROW][handling]" class="input-text" type="text"  value="$HANDLING" style="width: 100px" />
                <br /><strong>[<?php echo $this->getSuffix('handling', true) ?>]</strong>
            </td>
            <?php endif ?>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][sort_order]" value="$SORT_ORDER" style="width:50px" />
            </td>
            <td>
                <button type="button" class="scalable delete delete-fieldset"><span>&nbsp;</span></button>
            </td>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th colspan="<?php echo 1*$columnsCount?>" class="a-left">
                <div class="left"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span>+ <?php echo Mage::helper('udropship')->__('Add Rate') ?></span></button></div>
            </th>
        </tr>
        </tfoot>
        <tbody class="<?php echo $this->suffixId('body')?>">
        </tbody>
    </table>

    </td>
    <td<?php if ($_element->getNote()): ?> class="note"<?php endif ?> id="note_<?php echo $_element->getId()?>"><small><?php echo $_element->getNote()?$_element->getNote():'&nbsp;' ?></small></td>
</tr>

<style type="text/css">
</style>

<script type="text/javascript">
    //<![CDATA[
    (function ()
    {
        var lastRowNum = 0;
        var tbody = $$('#<?php echo $this->suffixId('cfgTable')?> tbody.<?php echo $this->suffixId('body')?>')[0]

        function addRow(inData)
        {
            var rowHtml = $('<?php echo $this->suffixId('rowTpl')?>').innerHTML
            var data = {
                delivery_type_id: '',
                customer_shipclass_id: '',
                customer_group_id: '',
                cost: '0',
                additional: '0',
                handling: '0',
                sort_order: '0'
            }
            Object.extend(data, inData);
            data.row = ++lastRowNum;

            var isIE = (/msie [1-8]\./i).test(navigator.userAgent);
            var numericVars = ['sort_order','cost','additional','handling','delivery_type_id'];
            var forcedNumericVars = [];
            var keys = $H(data).keys().sortBy(function(s){return (''+s).length}).reverse();
            for (j=0; j<keys.length; j++) {
                var i=keys[j];
                value = data[i] || ''
                if (-1 != numericVars.indexOf(i) && data[i]
                    || -1 != forcedNumericVars.indexOf(i)
                    ) {
                    value *= 1;
                    data[i] = value;
                }
                if (i!=='row' && isIE) value = '"'+value+'"';
                rowHtml = rowHtml.replace(new RegExp('\\$'+i.toUpperCase(), 'g'), value)
            }
            var regExTpl = [
                new Template('<option (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>]))){2})'),
                new Template('<option $1 selected="selected"'),
                new Template('<input (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>])|type="?checkbox"?)){3})'),
                new Template('<input $1 checked="checked"')
            ];
            var selectFields = $H({customer_shipclass_id:1,customer_group_id:1,delivery_type_id:0});
            selectFields.each(function(pair){
                var varsForEval, value=data[pair.key], key=pair.key;
                for (var rxIdx=0; rxIdx<regExTpl.length; rxIdx+=2) {
                    varsForEval = [];
                    if (pair.value) {
                        if (!Object.isArray(value)) {
                            value = String.interpret(value).split(',');
                        }
                        value.each(function(val){
                            varsForEval.push({key: RegExp.escape(key), value: RegExp.escape(val)});
                        })
                    } else {
                        varsForEval.push({key: RegExp.escape(key), value: RegExp.escape(value)});
                    }
                    for (var vfeIdx=0; vfeIdx<varsForEval.length; vfeIdx++) {
                        var varForEval = varsForEval[vfeIdx];
                        var rxFind = regExTpl[rxIdx].evaluate(varForEval);
                        var rxReplace = regExTpl[rxIdx+1].evaluate(varForEval);
                        rowHtml = rowHtml.replace(new RegExp(rxFind, 'i'), rxReplace);
                    }
                }
            });
            tbody.insert('<tr>'+rowHtml+'</tr>');
            var trs = tbody.childElements()
            var tr = trs[trs.length-1]
            tr.addClassName(lastRowNum%2 ? 'odd' : 'even')
            var del = $(tr).select('button.delete-fieldset')[0];
            if (del) {
                $(del).observe('click', function(e) { e.stop(); $(del.parentNode.parentNode).remove() })
            }
        }

        $('<?php echo $this->suffixId('addBtn')?>').observe('click', function(e) { e.stop(); addRow() });

        <?php if (is_array($fValue)): foreach ($fValue as $fV): ?>
        addRow(<?php echo Zend_Json::encode($fV) ?>);
        <?php endforeach; endif; ?>
    })();
    //]]>
</script>