<?php if (!Mage::registry('current_category')) return ?>

<?php
    //Current Category
    $currentCat = Mage::registry('current_category');
    
    //Current Category ID
    $currentCatID = Mage::registry('current_category')->getID();

    //Current Category Name
    $currentCatName = Mage::registry('current_category')->getName();
    
    //Parent Category ID
    $parentCatID = $currentCat->getParentId();
    
    //Parent Category Name
    $parentCatName = $this->getCurrentCategory()->getParentCategory()->getName();

    if($currentCatName == 'Catalogs') {
        //Get Current Child Categories
        $_categories = $this->getCurrentChildCategories();

        //Categories Count
        $_count = is_array($_categories)?count($_categories):$_categories->count();
        
        if($_count > 0) { ?>
            <?php 
                foreach ($_categories as $_category) {
                    //Category ID
                    $catID = $_category->getID();

                    //Category Name
                    $catName =  $_category->getName();

                    //Category Active Status
                    $isActive = $_category->getIsActive();

                    //Category URL
                    $catURL = $_category->getURL();

                    $catDetailArry[] = array('cat_id' => $catID,'cat_name' => $catName,'is_active' => $isActive,'cat_url' => $catURL);
                }

                function cmp($a,$b) {
                    return strcmp($a['cat_name'], $b['cat_name']);
                }

                usort($catDetailArry, cmp);
            ?>
            <div class="block block-layered-nav">
                <div class="block-title">
                    <strong><span><?php echo $this->__('Browse By') ?></span></strong>
                </div>
                <div class="block-content">
                    <dl id="narrow-by-list2" class="inner-categroy-list">
                        <dt><?php echo $this->__('Brands') ?></dt>
                        <dd>
                            <ol>
                                <?php foreach ($catDetailArry as $key => $catValue) { ?>
                                        <?php
                                            /*************************/
                                           /**  Get PDF File Count **/
                                          /*************************/
                                          $fileCount = 0;

                                            $uploadedDigitalCatlogPath = Mage::getBaseDir('media') . DS . 'digital_catalog'. DS . $catValue['cat_id'] . DS;

                                            if(file_exists($uploadedDigitalCatlogPath)) {
                                                //Search For PDF Files In A Directory
                                                $files = glob($uploadedDigitalCatlogPath."*.pdf");

                                                if($files) {
                                                    $fileCount = count($files);
                                                }
                                            }

                                            if($fileCount > 0 && $catValue['is_active'] == 1) { ?>
                                                <li>
                                                    <a href="<?php echo $catValue['cat_url']; ?>"<?php if ($catValue['is_active'] == 1) { ?> class="current"<?php } ?>><?php echo $this->escapeHtml($catValue['cat_name']); ?></a>
                                                </li>
                                            <?php } ?>
                                <?php } ?>
                            </ol>
                        </dd>
                    </dl>
                    <script type="text/javascript">decorateDataList('narrow-by-list2')</script>
                </div>
            </div>
        <?php }
    } elseif ($parentCatName == 'Catalogs') {
        $loadCategory = Mage::getModel('catalog/category')->load($currentCat->getParentId());

        $subCat = explode(',',$loadCategory->getChildren());
        
        //Sub Category Count
        $count = is_array($subCat) ? count($subCat) : $subCat->count();

        if($count > 0) { ?>
            <?php 
                foreach ($subCat as $subCatID) {
                    $cat = Mage::getModel('catalog/category')->load($subCatID);

                    //Category Name
                    $catName =  $cat->getName();

                    //Category Active Status
                    $isActive = $cat->getIsActive();

                    //Category URL
                    $catURL = $cat->getURL();

                    $catDetailArry[] = array('cat_id' => $subCatID,'cat_name' => $catName,'is_active' => $isActive,'cat_url' => $catURL);
                }

                function cmp($a,$b) {
                    return strcmp($a['cat_name'], $b['cat_name']);
                }

                usort($catDetailArry, cmp);
            ?>
            <div class="block block-layered-nav">
                <div class="block-title">
                    <strong><span><?php echo $this->__('Browse By') ?></span></strong>
                </div>
                <div class="block-content">
                    <dl id="narrow-by-list2" class="inner-categroy-list">
                        <dt><?php echo $this->__('Brands') ?></dt>
                        <dd>
                            <ol>
                                <?php foreach ($catDetailArry as $key => $catValue) { ?>
                                        <?php
                                            /*************************/
                                           /**  Get PDF File Count **/
                                          /*************************/
                                          $fileCount = 0;

                                            $uploadedDigitalCatlogPath = Mage::getBaseDir('media') . DS . 'digital_catalog'. DS . $catValue['cat_id'] . DS;

                                            if(file_exists($uploadedDigitalCatlogPath)) {
                                                //Search For PDF Files In A Directory
                                                $files = glob($uploadedDigitalCatlogPath."*.pdf");

                                                if($files) {
                                                    $fileCount = count($files);
                                                }
                                            }

                                            if($fileCount > 0 && $catValue['is_active'] == 1) { ?>
                                                <li>
                                                    <?php if($catValue['cat_id'] == $currentCatID) { ?>
                                                        <span style="color:#f4a137"><?php echo $this->escapeHtml($catValue['cat_name']); ?></span>
                                                    <?php } else {?>
                                                        <a href="<?php echo $catValue['cat_url']; ?>"<?php if ($catValue['is_active'] == 1) { ?> class="current"<?php } ?>><?php echo $this->escapeHtml($catValue['cat_name']); ?></a>
                                                    <?php } ?>
                                                </li>
                                            <?php } ?>
                                <?php } ?>
                            </ol>
                        </dd>
                    </dl>
                    <script type="text/javascript">decorateDataList('narrow-by-list2')</script>
                </div>
            </div>
        <?php }
    } else {
        //Get Current Child Categories
        $_categories = $this->getCurrentChildCategories();

        //Categories Count
        $_count = is_array($_categories)?count($_categories):$_categories->count();

        if($_count > 0) { ?>
            <div class="block block-layered-nav">
                <div class="block-title">
                    <strong><span><?php echo $this->__('Browse By') ?></span></strong>
                </div>
                <div class="block-content">
                    <dl id="narrow-by-list2" class="inner-categroy-list">
                        <dt><?php echo $this->__('Category') ?></dt>
                        <dd>
                            <ol>
                                <?php foreach ($_categories as $_category) { ?>
                                    <?php if($_category->getIsActive()) { ?>
                                        <li>
                                            <a href="<?php echo $this->getCategoryUrl($_category) ?>"<?php if ($this->isCategoryActive($_category)): ?> class="current"<?php endif; ?>><?php echo $this->escapeHtml($_category->getName()) ?></a> (<?php echo $_category->getProductCount() ?>)
                                        </li>
                                    <?php } ?>
                                <?php } ?>
                            </ol>
                        </dd>
                    </dl>
                    <script type="text/javascript">decorateDataList('narrow-by-list2')</script>
                </div>
            </div>
        <?php }
    }
?>