<?php
$_tsHlp = Mage::helper('udtiership');
$cShipClass = Mage::getSingleton('udshipclass/source')->setPath('customer_ship_class')->toOptionHash();
$_yesnoOpts = Mage::getSingleton('udropship/source')->setPath('yesno')->toOptionHash();
$store = Mage::app()->getDefaultStoreView();
?>

<div class="grid" style="width:500px">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:500px">
        <col width="200" />
        <col width="100" />
        <col width="50" />
        <col width="50" />
        <thead>
        <tr class="headings">
            <th><?php echo Mage::helper('udropship')->__('Customer') ?></th>
            <th><?php echo Mage::helper('udropship')->__('Surcharge') ?></th>
            <th><?php echo Mage::helper('udropship')->__('Sort Order') ?></th>
            <th><?php echo Mage::helper('udropship')->__('Action') ?></th>
        </tr>
        <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
            <td>
                <select name="<?php echo $this->getFieldName()?>[$ROW][customer_shipclass_id][]" style="width:200px">
                    <option alt="customer_shipclass_id" value="*"><?php echo Mage::helper('udropship')->__('*** All ***')?></option>
                    <?php foreach ($cShipClass as $cscId=>$cscLabel): ?>
                        <option alt="customer_shipclass_id" value="<?php echo $cscId?>"><?php echo $this->htmlEscape($cscLabel)?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][surcharge]" value="$SURCHARGE" style="width:100px" />
                <?php echo $this->getSuffix() ?>
            </td>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][sort_order]" value="$SORT_ORDER" style="width:70px" />
            </td>
            <td>
                <button type="button" class="scalable delete"><span></span></button>
            </td>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th colspan="4" class="a-left">
                <div class="left"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span><?php echo Mage::helper('udropship')->__('Add Surcharge') ?></span></button></div>
            </th>
        </tr>
        </tfoot>
        <tbody>
        </tbody>
    </table>

</div>

<style type="text/css">
</style>