<?php
$catname = Mage::registry('current_category')->getName();
$catimage = Mage::registry('current_category')->getImage();
$mediaurl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$imageurl = $mediaurl."catalog/category/".$catimage;
?>
<!-- <div class="heading-title"><?php //echo $catname;?></div> -->
<div class="categorybanner">
<img src = "<?php echo $imageurl;?>"/>
</div>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div class="category-products category-list-dy">
<ul class="products-grid">
<?php
$_categories=$this->getCurrentChildCategories();

if($_categories->count()):
$categorycount = 0;
foreach ($_categories as $_category):
if($_category->getIsActive()):
$cur_category=Mage::getModel('catalog/category')->load($_category->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category);
$catName = $this->getCurrentCategory()->getName();
if ($categorycount == 0){
$class = "first";
}
elseif ($categorycount == 25){
$class = "last";
}
else{
$class = "";
}
?>

<?php 
$banner =  $cur_category->getCatbanner();
$caturl = $mediaurl."catalog/category/".$banner;

?>

<li class="item col-lg-3 col-md-3 col-sm-6 col-xs-12 <?=$class?>">
    <div class="item-inner">
        <div class="product-image">
            <a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>">
                <?php if(($catname == "Products") || ($catname == "Services") || ($catname == "Consultants") ){ ?>
                <img src="<?php echo $caturl; ?>"
                <?php } else{ ?>
                <img src="<?php echo $cur_category->getImageUrl(); ?>"
                <?php } ?>
                 width="100" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /></a>
        </div>
        <div class="product-name"><a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>"><?php echo $this->htmlEscape($_category->getName()) ?></a></div>
    </div>
</li>
<?php
endif;
if($categorycount == 25){
$categorycount = 0;
echo "</ul>\n\n<ul class=\"products-grid\">";
}
else{
$categorycount++;
}
endforeach;
endif;
?>
</ul>
</div>