<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="my-account">
<?php $_quotes = $this->getQuotes(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Quotes') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_quotes->getSize()): ?>
<table class="data-table my-account-table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th class=""><?php echo $this->__('Quote #') ?></th>
            <th class=""><?php echo $this->__('Date') ?></th>
            <th class=""><?php echo $this->__('Request By') ?></th>
            <th class=""><?php echo $this->__('Quote Created By') ?></th>
            <th class=""><?php echo $this->__("Items")?></th>
            <th class=""><span class="nobr"><?php echo $this->__('Subtotal') ?></span></th>
            <th class=""><span class="nobr"><?php echo $this->__('Quote Total') ?></span></th>
            <th class="">Quote's</th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_quotes as $_quote): 
        $items = $_quote->getItemsCollection();
        ?>
        <tr>
            <td data-label="Quote"><?php echo $this->getQuoteIdFromQuote($_quote) ?></td>
            <td data-label="Date"><span class="nobr"><?php echo $this->formatDate($_quote->getCreatedAt()) ?></span></td>
            <td data-label="Request By"><?php echo $_quote->getQuoteRequestBy() ?></td>
            <td data-label="Quote By"><?php echo $_quote->getQuoteBy() ?></td>
            <td data-label="Items"><?php foreach ($items as $item){echo $item->name .'<br>';}?></td>
            <td data-label="Subtotal"><?php echo Mage::helper('core')->currency($_quote->getSubtotal(), true, false); ?></td>
            <td data-label="Quote Total"><?php echo Mage::helper('core')->currency($_quote->getGrandTotal(), true, false); ?></td>
            <td class="">
                <span class="nobr"><a href="<?php echo $this->getViewUrl($_quote) ?>"><?php echo $this->__('View Quote') ?></a>
                    <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_quote) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                    <?php /* if ($this->helper('sales/reorder')->canReorder($_quote)) : ?>
                    <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_quote) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                <?php endif */?>
                </span>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have received no quotes.'); ?></p>
<?php endif ?>
</div>
