
<script type="text/javascript">

Validation.add('validate-alpha-space','Please use letters only (a-z or A-Z) in this field',function(v)        {
    return Validation.get('IsEmpty').test(v) ||  /^[a-zA-Z ]+$/.test(v)
});

   Validation.add('validate-minlength','Characters entered are below minimum length',function(v, elm){
      
    var result = true;
    var classlist = elm.className.split(/\s+/);
    jQuery.each(classlist,function(index, name){
                  if ((/^minimum-length-[0-9]+$/i).test(name) && result) {
                                 var length = name.split('-')[2];
                           
                                 result = (v.length >= length);
                             }
      
                    });
    return result;

  });
  Validation.add('validate-maxlength','Characters entered are above maximum length',function(v, elm){
      
    var result = true;
    var classlist = elm.className.split(/\s+/);
    jQuery.each(classlist,function(index, name){
                  if ((/^maximum-length-[0-9]+$/i).test(name) && result){
                                 var length = name.split('-')[2];
                        
                                 result = (v.length <= length);
                             }
      
                    });
    return result;

  });


 function getFormattedDate(date){
    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear().toString().slice(2);
    return day + '/' + month + '/' + year;
} 


</script>   