(function($){$.fn.viewport=function(){var e=window,a='inner';if(!('innerWidth'in window)){a='client';e=document.documentElement||document.body;}
return{width:e[a+'Width'],height:e[a+'Height']};}
$.fn.getScrollbarWidth=function(){document.body.style.overflow='hidden';var width=document.body.clientWidth;document.body.style.overflow='scroll';width-=document.body.clientWidth;if(!width)width=document.body.offsetWidth-document.body.clientWidth;document.body.style.overflow='';return width;}
$.fn.detectDevice=function(){var width=$.fn.viewport().width;var scrollWidth=$().getScrollbarWidth();if(width>1200){return'wide';}else if(width>=992){return'normal';}else if(width>=768){return'tablet';}else if(width>0){return'mobile';}}
$.fn.updateDataElementClass=function(){var $this=$(this);currentdevice=(currentdevice)?currentdevice:$.fn.detectDevice();if($this.data('default'))return;else $this.data();$this.removeAttr('data-default data-wide data-normal data-tablet data-stablet data-mobile');if(!$this.data('default'))
$this.data('default',$this.attr('class'));if(!$this.data('default')||!currentdevice||!$this.data(currentdevice))
return;else{$this.removeClass($this.data('default'));$this.addClass($this.data(currentdevice));}}})(jQuery)
var currentdevice='';jQuery(document).ready(function($){var bootstrap_elements=$('[class*="span"]');bootstrap_elements.each(function(){var $this=$(this);$this.data();$this.removeAttr('data-default data-wide data-normal data-tablet data-stablet data-mobile');if(!$this.data('default'))
$this.data('default',$this.attr('class'));});function updateBootstrapElementClass(newdevice){if(newdevice==currentdevice)return;bootstrap_elements.each(function(){var $this=$(this);if(!$this.data('default')||(!$this.data(newdevice)&&(!currentdevice||!$this.data(currentdevice))))
return;if($this.data(currentdevice))$this.removeClass($this.data(currentdevice));else $this.removeClass($this.data('default'));if($this.data(newdevice))$this.addClass($this.data(newdevice));else $this.addClass($this.data('default'));});currentdevice=newdevice;};function getScrollbarWidth(){document.body.style.overflow='hidden';var width=document.body.clientWidth;document.body.style.overflow='scroll';width-=document.body.clientWidth;if(!width)width=document.body.offsetWidth-document.body.clientWidth;document.body.style.overflow='';return width;}
function viewport(){var e=window,a='inner';if(!('innerWidth'in window)){a='client';e=document.documentElement||document.body;}
return{width:e[a+'Width'],height:e[a+'Height']};}
function idforPriceOnMenu(){if($('.sm_megamenu_content .price-box .special-price span.special-price').length>0){$('.sm_megamenu_content .price-box .special-price span.special-price').each(function(){$(this).attr('id',$(this).attr('id')+'_onmenu');});}
if($('.sm_megamenu_content .price-box .regular-price').length>0){$('.sm_megamenu_content .price-box .regular-price').each(function(){$(this).attr('id',$(this).attr('id')+'_onmenu');});}}
idforPriceOnMenu();function detectDevice(){var width=viewport().width;if(width>1200){return'wide';}else if(width>=992){return'normal';}else if(width>=768){return'tablet';}else if(width>0){return'mobile';}}
updateBootstrapElementClass(detectDevice());$(window).resize(function(){if($.data(window,'detect-device-time'))
clearTimeout($.data(window,'detect-device-time'));$.data(window,'detect-device-time',setTimeout(function(){updateBootstrapElementClass(detectDevice());},200))});});jQuery(window).load(function(){function viewport(){var e=window,a='inner';if(!('innerWidth'in window)){a='client';e=document.documentElement||document.body;}
return{width:e[a+'Width'],height:e[a+'Height']};}});