<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="kit-login-form">
    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
<div class="page-title">
    <h1><?php echo $this->__('Registered Customers') ?></h1>
    <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
</div>

<div class="inputfiled iteminput"><br/>
    <input type="text" class="required-entry validate-email" placeholder="<?php echo $this->__('* Email Address') ?>" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email"/>
</div>
<div class="inputfiled iteminput">
    <input type="password" name="login[password]" class="required-entry validate-password" id="pass" title="<?php echo $this->__('* Password') ?>" />
</div>
<div class="buttons-set">
    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
</div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('kit-login-form', true);
    //]]>
</script>