<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            <h3><?php echo $post->getCreatedTime(); ?></h3>
        </div>
        <div class="postContent"><?php echo $post->getPostContent(); ?></div>

        <?php echo $this->getBookmarkHtml($post) ?>
        <?php if($this->getTagsHtml($post)) { ?><div class="tags"><?php echo $this->getTagsHtml($post) ?></div><?php } ?>
        <div class="postDetails">
       
            <?php if ($this->getCommentsEnabled()): ?>       
                <?php if($post->getCommentCount()){echo $post->getCommentCount();}  else { echo "0";} ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php if($post->getCommentCount()==0 || $post->getCommentCount()==1) { echo $this->__("Comment")?> <?php } else { echo $this->__("Comment")?><?php } ?></a> 
            <?php endif; ?> |
           

            <?php $postCats = $post->getCats(); ?>
                <?php /*if (!empty($postCats)): ?>
                    <?php echo Mage::helper('blog')->__('Posted in'); ?>
                    <?php foreach ($postCats as $data): ?>
                            <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php echo Mage::helper('blog')->__('Posted'); ?>
                <?php endif;*/ ?>

                <?php echo$this->__("Posted By"); ?> <?php echo $post->getUser(); ?></div>
    </div>
<?php endforeach; ?>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
