<?php
/**
 * Unirgy LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.unirgy.com/LICENSE-M1.txt
 *
 * @category   Unirgy
 * @package    Unirgy_Dropship
 * @copyright  Copyright (c) 2008-2009 Unirgy LLC (http://www.unirgy.com)
 * @license    http:///www.unirgy.com/LICENSE-M1.txt
 */
?>
<?php if ($_entity = $this->getEntity()): ?>
<div id="comments_block">
    <span class="field-row">
        <label class="normal" for="comment_status"><?php echo Mage::helper('udropship')->__('Status') ?></label><br/>
        <select name="comment[status]" class="select" id="comment_status">
        <?php foreach (Mage::getSingleton('udropship/source')->setPath('shipment_statuses')->toOptionHash() as $_code=>$_label): ?>
            <option value="<?php echo $_code ?>"<?php if($_code==$this->getEntity()->getUdropshipStatus()): ?> selected="selected"<?php endif; ?>><?php echo $_label ?></option>
        <?php endforeach; ?>
        </select>
        <script type="text/javascript">
        $('comment_status').origValue = $('comment_status').value
        </script>
    </span>
    <span class="field-row">
        <label class="normal" for="comment_comment"><?php echo Mage::helper('udropship')->__('Comment Text') ?></label>
        <textarea name="comment[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="comment_comment"></textarea>
    </span>
    <div class="f-left">
        <input name="comment[is_vendor_notified]" type="checkbox" id="vendor_comment_notify" value="1" /><label class="normal" for="vendor_comment_notify"> <?php echo Mage::helper('udropship')->__('Notify Vendor by Email') ?></label><br />
        <input name="comment[is_visible_to_vendor]" type="checkbox" id="comment_visible" value="1" /><label class="normal" for="comment_visible"> <?php echo Mage::helper('udropship')->__('Visible to Vendor') ?></label><br />
        <?php if ($this->canSendCommentEmail()): ?>
        <input name="comment[is_customer_notified]" type="checkbox" id="customer_comment_notify" value="1" /> <label class="normal" for="customer_comment_notify"><?php echo Mage::helper('udropship')->__('Notify Customer') ?></label>
        <?php endif; ?>
    </div>
    <div class="f-right">
        <?php echo $this->getChildHtml('submit_button') ?>
    </div>
    <div class="clear"></div>
    <ul class="note-list">
    <?php foreach ($_entity->getCommentsCollection(true) as $_comment): ?>
        <li>
            <strong><?php echo $this->helper('core')->formatDate($_comment->getCreatedAtDate(), 'medium') ?></strong>
            <?php echo $this->helper('core')->formatTime($_comment->getCreatedAtDate(), 'medium') ?><span class="separator">|</span><strong><?php echo $_comment->getUdropshipStatus() ?></strong><br/>
            <small><?php echo $this->helper('udropship')->__('Vendor') ?>
            <strong class="subdue">
                <?php if ($_comment->getIsVendorNotified()): ?>
                <?php echo $this->helper('sales')->__('Notified') ?>
                <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                <?php else: ?>
                <?php echo $this->helper('sales')->__('Not Notified') ?>
                <?php endif; ?>
            </strong></small>
            <span class="separator">|</span>
            <small><?php echo $this->helper('sales')->__('Customer') ?>
            <strong class="subdue">
                <?php if ($_comment->getIsCustomerNotified()): ?>
                <?php echo $this->helper('sales')->__('Notified') ?>
                <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                <?php else: ?>
                <?php echo $this->helper('sales')->__('Not Notified') ?>
                <?php endif; ?>
            </strong></small>
            <br/>
            <?php echo Mage::helper('core')->htmlEscape($_comment->getComment(), array('b','br','strong','i','u')) ?>
        </li>
    <?php endforeach; ?>
    </ul>
<script type="text/javascript">
function submitComment() {
    if (validateShipmentStatusSubmit()) {
        submitAndReloadArea($('comments_block').parentNode, '<?php echo $this->getUrl('adminhtml/udropshipadmin_shipment/addComment', array('shipment_id'=>$_entity->getId())) ?>')
    }
}

function validateShipmentStatusSubmit()
{
    if (<?php echo (int)Mage::helper('udropship')->isUdpoActive()?> == 0) return true;
    if ($('comment_status').value == $('comment_status').origValue) return true
    switch ($('comment_status').value) {
        case '<?php echo Unirgy_Dropship_Model_Source::SHIPMENT_STATUS_CANCELED ?>':
            return confirm('<?php echo Mage::helper('udropship')->__('This will cancel shipment (if possible).') ?>');
        case '<?php echo Unirgy_Dropship_Model_Source::SHIPMENT_STATUS_SHIPPED ?>':
            return confirm('<?php echo Mage::helper('udropship')->__('This will mark shipment as shipped (and if possible change PO status as well).') ?>');
        case '<?php echo Unirgy_Dropship_Model_Source::SHIPMENT_STATUS_DELIVERED ?>':
            return confirm('<?php echo Mage::helper('udropship')->__('This will mark shipment as delivered (and if possible change PO status as well).') ?>');
        default:
            return true;
    }
}

if ($('submit_comment_button')) {
    $('submit_comment_button').observe('click', submitComment);
}
</script>
</div>
<?php endif; ?>
