<?php
/*------------------------------------------------------------------------
 # SM Basic Products - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$list = $this->_getProducts();
$helper = Mage::helper('basicproducts/data');
if (!empty($list)) {
	$uniqued = 'sm_basic_products_' . time() . rand();

	$class_respl = 'bs-resp01-' . $this->_getConfig('nb_column1', 6) . ' bs-resp02-' . $this->_getConfig('nb_column2', 4) . ' bs-resp03-' . $this->_getConfig('nb_column3', 2) . ' bs-resp04-' . $this->_getConfig('nb_column4', 1);

	?>

	<?php if( $this->_getConfig('basicproducts_title_text') ){ ?>
		<div class="basicproducts_title_text">
			<?php echo $this->_getConfig('basicproducts_title_text','Basic Products Title'); ?>
		</div>
	<?php } ?>
	<?php if ( $this->_getConfig('pretext') != null ) { ?>
		<div class="bs-pretext">
			<?php echo $this->_getConfig('pretext'); ?>
		</div>
	<?php } ?>

	<!--[if lt IE 9]>
	<div id="<?php echo $uniqued; ?>" class="sm-basic-products  msie lt-ie9"><![endif]-->
	<!--[if IE 9]>
	<div id="<?php echo $uniqued; ?>" class="sm-basic-products  msie"><![endif]-->
	<!--[if gt IE 9]><!-->
	<div id="<?php echo $uniqued; ?>" class="sm-basic-products"><!--<![endif]-->
		<!-- Begin bs-items     -->
		<div class="bs-items <?php echo $class_respl; ?> ">
			<?php  $j = 0;
			foreach ($list as $_product) {

				$j++;
				$show_line = ($this->_getConfig('showline') == 1) ? ' bs-show-line' : '';
				$last_class = ($j == count($list)) ? ' last' : '';
				?>
				<!-- Begin bs-item-cf -->
				<div class="bs-item cf">
					<!-- Begin bs-item-inner -->
					<div class="bs-item-inner">
						
						<?php if ( $_product->_image ) { ?>
							<div class="bs-image">
								<a href="<?php echo $_product->link ?>"
								   title="<?php echo $_product->title; ?>"
									<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
									>
									<img src="<?php echo $_product->_image; ?>"
									     title="<?php echo $_product->title; ?>"
									     alt="<?php echo $_product->title; ?>"
										>
								</a>
							</div>
						<?php } ?>
						
						<!-- Begin bs-content -->
						<div class="bs-content">

							<?php if( (int)$this->_getConfig('product_title_display',1) ) { ?>
								<div class="bs-title">
									<a href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>"
										<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
										>
										<?php echo $helper->truncate($_product->title,$this->_getConfig('product_title_maxlength'));?>
									</a>
								</div>
							<?php } ?>

							<?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->description) != '') { ?>
								<div class="bs-description">
									<?php echo $_product->_description; ?>
								</div>
							<?php } ?>


					

							<?php if ($this->_getConfig('product_source') != 'media') { ?>
								<?php if ((int)$this->_getConfig('product_reviews_count', 1)){ ?>
									<div class="bs-review">
										<?php
										$this->addReviewSummaryTemplate('sm', 'sm/basicproducts/default_summary.phtml');
										echo $this->getReviewsSummaryHtml($_product, 'sm', false);
										?>
									</div>
								<?php } ?>

								<?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
									<div class="bs-price">
										<div class="sale-price">
											<?php echo $this->getPriceHtml($_product, true); ?>
										</div>
									</div>
								<?php } ?>

								
							<?php } ?>



							<?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
								<div class="bs-detail">
									<a href="<?php echo $_product->link ?>"
									   title="<?php echo $_product->title; ?>"
										<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
										>
										<?php echo $this->_getConfig('product_readmore_text','Details'); ?>
									</a>
								</div>
							<?php } ?>
						</div>
						<!-- End bs-content -->
					</div>
					<!-- End bs-item-inner -->
				</div><!-- End bs-item-cf -->
				<?php
				$clear = 'clr1';
				if ($j % 2 == 0) $clear .= ' clr2';
				if ($j % 3 == 0) $clear .= ' clr3';
				if ($j % 4 == 0) $clear .= ' clr4';
				if ($j % 5 == 0) $clear .= ' clr5';
				if ($j % 6 == 0) $clear .= ' clr6';
				?>
				<div class="<?php echo $clear; ?>"></div>
			<?php } ?>
		</div>
		<!-- End bs-items -->
	</div><!-- End Sm-basic-products -->
	<?php if ($this->_getConfig('posttext') != null) { ?>
		<div class="bs-posttext">
			<?php echo $this->_getConfig('posttext'); ?>
		</div>
	<?php } ?>


<?php
} else {
	echo 'Has no content to show!';
}?>