<?php
$_element = $this->getElement();
$this->setFieldName($_element->getName());
$fValue = $_element->getValue();
?>

<div class="grid">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:70px">
        <col width="200" />
        <col width="300" />
        <col width="300" />
        <col width="100" />
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('udropship')->__('Fieldset Title/Sort Order') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Top/Bottom wide fields') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Left/Right column fields') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Action') ?></th>
            </tr>
            <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
                <td>
                    <h3><?php echo Mage::helper('udropship')->__('Title')?></h3>
                    <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$$ROW][title]" value="$$TITLE" style="width:200px" />
                    <h3><?php echo Mage::helper('udropship')->__('Sort Order')?></h3>
                    <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$$ROW][sort_order]" value="$$SORT_ORDER" style="width:70px" />
                </td>
                <td>
                    <h3><?php echo Mage::helper('udropship')->__('Top Wide Fields')?></h3>

                    <div class="top_columns_def-fieldset">
                    <?php 
                        $fcBlock = $this->getFieldContainerBlock($this->getFieldName().'[$$ROW][top_columns_def]');
                        echo $fcBlock->toHtml();
                    ?>
                    </div>

                    <br /><br />

                    <h3><?php echo Mage::helper('udropship')->__('Bottom Wide Fields')?></h3>
                
                    <div class="bottom_columns_def-fieldset">
                    <?php 
                        $fcBlock = $this->getFieldContainerBlock($this->getFieldName().'[$$ROW][bottom_columns_def]');
                        echo $fcBlock->toHtml();
                    ?>
                    </div>

                </td>
                <td>
                    <h3><?php echo Mage::helper('udropship')->__('Left Column Fields')?></h3>

                    <div class="left_columns_def-fieldset">
                    <?php 
                        $fcBlock = $this->getFieldContainerBlock($this->getFieldName().'[$$ROW][left_columns_def]');
                        echo $fcBlock->toHtml();
                    ?>
                    </div>

                    <br /><br />

                    <h3><?php echo Mage::helper('udropship')->__('Right Column Fields')?></h3>
                
                    <div class="right_columns_def-fieldset">
                    <?php 
                        $fcBlock = $this->getFieldContainerBlock($this->getFieldName().'[$$ROW][right_columns_def]');
                        echo $fcBlock->toHtml();
                    ?>
                    </div>

                </td>
                <td>
                    <button type="button" class="scalable delete delete-fieldset"><span><?php echo Mage::helper('udropship')->__('Remove') ?></span></button>
                </td>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th colspan="5" class="a-left">
                    <div class="left"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span>+ <?php echo Mage::helper('udropship')->__('Add Fieldset') ?></span></button></div>
                </th>
            </tr>
        </tfoot>
        <tbody class="fieldset_config_body">
        </tbody>
    </table>

</div>

<style type="text/css">
</style>

<script type="text/javascript">
//<![CDATA[
(function ()
{
    window['udprodFields'] = <?php echo $this->getEditFieldsConfigSelect2Json()?>;
    var lastRowNum = 0;
    var tbody = $$('#<?php echo $this->suffixId('cfgTable')?> tbody.fieldset_config_body')[0]

    function addRow(inData)
    {
        var rowHtml = $('<?php echo $this->suffixId('rowTpl')?>').innerHTML
        var data = {
            title: '',
            sort_order: '0'
        }
        Object.extend(data, inData);
        data.row = ++lastRowNum;

        var isIE = (/msie [1-8]\./i).test(navigator.userAgent);
        var numericVars = ['sort_order'];
        var forcedNumericVars = [];
        var keys = $H(data).keys().sortBy(function(s){return (''+s).length}).reverse();
        for (j=0; j<keys.length; j++) {
            var i=keys[j];
            value = data[i] || ''
            if (-1 != numericVars.indexOf(i) && data[i]
                || -1 != forcedNumericVars.indexOf(i)
            ) {
                value *= 1;
                data[i] = value;
            }
            if (i!=='row' && isIE) value = '"'+value+'"';
            rowHtml = rowHtml.replace(new RegExp('\\$\\$'+i.toUpperCase(), 'g'), value)
        }
        var regExTpl = [
            new Template('<option (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>]))){2})'),
            new Template('<option $1 selected="selected"'),
            new Template('<input (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>])|type="?checkbox"?)){3})'),
            new Template('<input $1 checked="checked"')
        ];
        /*
        [].each(function(key){
            for (var rxIdx=0; rxIdx<regExTpl.length; rxIdx+=2) {
                var varForEval = {key: key, value: data[key]};
                var rxFind = regExTpl[rxIdx].evaluate(varForEval);
                var rxReplace = regExTpl[rxIdx+1].evaluate(varForEval);
                rowHtml = rowHtml.replace(new RegExp(rxFind, 'i'), rxReplace);
            }
        });
        */
        tbody.insert('<tr>'+rowHtml+'</tr>')
        var trs = tbody.childElements()
        var tr = trs[trs.length-1]
        tr.addClassName(lastRowNum%2 ? 'odd' : 'even')
        var del = $(tr).select('button.delete-fieldset')[0];
        if (del) {
            $(del).observe('click', function(e) { e.stop(); $(del.parentNode.parentNode).remove() })
        }
        (function () {
        $A(['top_columns_def','bottom_columns_def','left_columns_def','right_columns_def']).each(function(colKey){
            if (Object.isArray(data[colKey]) && data[colKey].length>0) {
                var colAddBtnId = tr.down('.'+colKey+'-fieldset button.add').id;
                $A((data[colKey])).each(function(colRowData){
                    window[colAddBtnId+'udpAddRow'](colRowData);
                });
            }
        });
        }).defer();
    }

    $('<?php echo $this->suffixId('addBtn')?>').observe('click', function(e) { e.stop(); addRow() });

<?php if (is_array($fValue)): foreach ($fValue as $fV): ?>
    addRow(<?php echo Zend_Json::encode($fV) ?>);
<?php endforeach; endif; ?>
})();
//]]>
</script>




