<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                    Login / Registration
                </a><i class="indicator glyphicon glyphicon-chevron-down  pull-right"></i>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">

            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                    Email Verification
                </a><i class="indicator glyphicon glyphicon-chevron-up  pull-right"></i>
            </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">

            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                    Mobile Varification
                </a><i class="indicator glyphicon glyphicon-chevron-up pull-right"></i>
            </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body">

            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse4">
                   Company Information
                </a><i class="indicator glyphicon glyphicon-chevron-up pull-right"></i>
            </h4>
        </div>
        <div id="collapse4" class="panel-collapse collapse">
            <div class="panel-body">
                <div class="myac-tab-inner">
                    <div class="item-fields">
                        <div class="inputfiled iteminput">
                            <textarea class="required-entry" placeholder="* Billing Address" title="Billing Address" type="text"></textarea>
                            <p>Upload Address Proof Below To Verify :</p>
                            <div class="file-upload-outer">
                                <input type="file" name="fileToUpload" id="fileToUpload">
                            </div>
                        </div>
                        <div class="inputfiled iteminput">
                            <textarea class="required-entry" placeholder="* Shipping Address" title="Shipping Address" type="text"></textarea>
                            <p>Upload Address Proof Below To Verify :</p>
                            <div class="file-upload-outer">
                                <input type="file" name="fileToUpload" id="fileToUpload">
                            </div>
                        </div>
                        <div class="inputfiled row">
                            <div class="col-md-4">
                                <div>
                                    <input title="PAN Number" placeholder="* PAN Number" class="required-entry" type="text">
                                </div>
                                <p>Upload PAN Proof Below To Verify :</p>
                                <div class="file-upload-outer">
                                    <input type="file" name="fileToUpload" id="fileToUpload">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div>
                                    <input title="VAT Number" placeholder="* VAT Number" class="required-entry" type="text">
                                </div>
                                <p>Upload VAT Proof Below To Verify :</p>
                                <div class="file-upload-outer">
                                    <input type="file" name="fileToUpload" id="fileToUpload">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div>
                                    <input title="TIN Number" placeholder="* TIN Number" class="required-entry" type="text">
                                </div>
                                <p>Upload TIN Proof Below To Verify :</p>
                                <div class="file-upload-outer">
                                    <input type="file" name="fileToUpload" id="fileToUpload">
                                </div>
                            </div>
                        </div>
                        <div class="inputfiled">
                            <select class="">
                                <option value="">* Type of Business</option>
                                <option value="1">Test 1</option>
                                <option value="2">Test 2</option>
                            </select>
                        </div>
                        <div class="inputfiled iteminput">
                            <input class="required-entry" placeholder="* Website URL" title="Website URL" type="text">
                        </div>
                        <div class="buttons-set">
                            <button type="submit" title="Submit" class="button"><span><span>Next</span></span></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse5">
                    Catalog
                </a><i class="indicator glyphicon glyphicon-chevron-up pull-right"></i>
            </h4>
        </div>
        <div id="collapse5" class="panel-collapse collapse">
            <div class="panel-body">
                <div class="myac-tab-inner">
                    <div class="item-fields">
                        <form action="" id="">

                            <div class="page-title">
                                <h1>Select Product Categories</h1>
                            </div>

                            <div class="item-fields-checkbox-div">
                                <ul>
                                    <li>
                                        <span class="expandfilter expand-active"></span>
                                        <a class="custom-checkbox">
                                            <input class="check_parent" type="checkbox">
                                            <label>Abrasives</label>
                                        </a>
                                        <ul>
                                            <li>
                                                <a class="custom-checkbox">
                                                    <input class="check_child" type="checkbox">
                                                    <label>test 1</label>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="custom-checkbox">
                                                    <input class="check_child" type="checkbox">
                                                    <label>test 2</label>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="custom-checkbox">
                                                    <input class="check_child" type="checkbox">
                                                    <label>test 3</label>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <span class="expandfilter expand-active"></span>
                                        <a class="custom-checkbox">
                                            <input class="check_parent" type="checkbox">
                                            <label>Abrasives</label>
                                        </a>
                                        <ul>
                                            <li>
                                                <a class="custom-checkbox">
                                                    <input class="check_child" type="checkbox">
                                                    <label>test 1</label>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="custom-checkbox">
                                                    <input class="check_child" type="checkbox">
                                                    <label>test 2</label>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <span class="expandfilter expand-active"></span>
                                        <a class="custom-checkbox">
                                            <input class="check_parent" type="checkbox">
                                            <label>Abrasives</label>
                                        </a>
                                        <ul>
                                            <li>
                                                <a class="custom-checkbox">
                                                    <input class="check_child" type="checkbox">
                                                    <label>test 1</label>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="custom-checkbox">
                                                    <input class="check_child" type="checkbox">
                                                    <label>test 2</label>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>

                            <div class="inputfiled iteminput">
                                <p>Upload Product Catalogue :</p>
                                <div class="file-upload-outer">
                                    <input type="file" name="fileToUpload" id="fileToUpload">
                                </div>
                            </div>
                            <div class="buttons-set">
                                <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse6">
                    Documents Verification
                </a><i class="indicator glyphicon glyphicon-chevron-up pull-right"></i>
            </h4>
        </div>
        <div id="collapse6" class="panel-collapse collapse">
            <div class="panel-body">

            </div>
        </div>
    </div>
</div>




<script>
    jQuery( document ).ready(function($) {
        $('.item-fields-checkbox-div .expandfilter').click(function() {
            $(this).toggleClass('expand-active');
            $(this).parent().find('ul').slideToggle();
        });
        $(".custom-checkbox .check_parent").change(function(){
            $(this).parent().next('ul').find(".check_child").prop('checked', $(this).prop("checked"));
        });
        $(".custom-checkbox .check_child").change(function(){
            var parent = $(this).closest('ul');
            var status = parent.find('.check_child').not(':checked').length === 0;
            parent.prev(".custom-checkbox").find('.check_parent').prop('checked', status);
        });
    })
</script>

