<?php $_product = Mage::getModel('catalog/product')->load($_GET['product_id']);
$min = $_product->getMinimumOrderQuantity();

 ?>


<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">

    <!-- If the page displayed after rejecting a quote -->
    <?php if ($_GET['rejectquoteid']): ?>
        <h1><?php echo Mage::helper('quote2sales')->__('Quote rejected successfully, would you like to add new request') ?></h1>
    <?php else: ?>
        <h1><?php echo Mage::helper('quote2sales')->__('Request for Quote') ?></h1>
    <?php endif; ?>
</div>
<div class="container">
    <div class="row">
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <div class="col-lg-6">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('quote2sales')->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                 <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('quote2sales')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('quote2sales')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>

                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('quote2sales')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('quote2sales')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->getUserName()) ?>" class="input-text validate-xss-comment validate-alphanum-with-spaces required-entry" type="text" />
                    </div>
                </div>
               
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('quote2sales')->__('Quantity') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('quote2sales')->__('Telephone') ?>" value="<?php echo $min; ?>" class="required-entry validate-phonenumber validate-telephone validate-length minimum-length-1 maximum-length-15 input-text" type="text" maxlength="15" />
                </div>
            </li>
            <li>
                <label for="demo"><?php echo Mage::helper('quote2sales')->__('Target Price') ?></label>
                <div class="input-box">
                    <input name="demo" id="demo" title="<?php echo Mage::helper('quote2sales')->__('demo') ?>" value="" class="required-entry validate-phonenumber validate-telephone validate-length minimum-length-1 maximum-length-15 input-text" type="text" maxlength="15" />
                </div>
            </li>

            <li>    
                <label for="deliverydate"><?php echo Mage::helper('quote2sales')->__('Delivery Date') ?></label>
                <div class="input-box">
                    <input name="deliverydate" id="deliverydate" title="<?php echo Mage::helper('quote2sales')->__('deliverydate') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li>


            <li>    
                <label for="telephone"><?php echo Mage::helper('quote2sales')->__('Delivery Location') ?></label>
                <div class="input-box">
                    <input name="deliverylocation" id="deliverylocation" title="<?php echo Mage::helper('quote2sales')->__('deliverylocation') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li>

               

            <li>    
                <label for="paymentterms"><?php echo Mage::helper('quote2sales')->__('Payment Terms') ?></label></br>
                 <select class="paymentterms">
                    <option value="100% Advance on order" >100% Advance on order</option>
                    <option value="50% Advance on order + Balance on Shipment" >50% Advance on order + Balance on Shipment</option>
                </select>
                <div class="input-box" style="display:none;">
                    <input name="paymentterms" id="paymentterms" title="<?php echo Mage::helper('quote2sales')->__('paymentterms') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li>


                <li>    
                <label for="shippingmethod"><?php echo Mage::helper('quote2sales')->__('Shipping Method') ?></label></br>
                <select class="shippingmethod">
                    <option value="By Road" >By Road</option>
                    <option value="By Air" >By Air</option>
                    <option value="By Sea" >By Sea</option>
                </select>
                <div class="input-box" style="display:none;">
                    <input name="shippingmethod" id="shippingmethod" title="<?php echo Mage::helper('quote2sales')->__('shippingmethod') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li>





            <!-- <li>    
                <label for="paymentroad"><?php //echo Mage::helper('quote2sales')->__('paymentroad') ?></label>
                <div class="input-box">
                    <input name="paymentroad" id="paymentroad" title="<?php //echo Mage::helper('quote2sales')->__('paymentroad') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li>


            <li>    
                <label for="ver"><?php //echo Mage::helper('quote2sales')->__('ver') ?></label>
                <div class="input-box">
                    <input name="ver" id="ver" title="<?php //echo Mage::helper('quote2sales')->__('ver') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li>


            <li>    
                <label for="deliverydate"><?php //echo Mage::helper('quote2sales')->__('deliverydate') ?></label>
                <div class="input-box">
                    <input name="deliverydate" id="deliverylocation" title="<?php //echo Mage::helper('quote2sales')->__('deliverydate') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li>


        

            
 -->



            <!-- -->

            <!--  <li>    
                <label for="paymentterms"><?php //echo Mage::helper('quote2sales')->__('paymentterms') ?></label>
                <div class="input-box">
                    <input name="paymentterms" id="paymentterms" title="<?php //echo Mage::helper('quote2sales')->__('paymentterms') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li>

             <li>    
                <label for="shippingmethod"><?php //echo Mage::helper('quote2sales')->__('shippingmethod') ?></label>
                <div class="input-box">
                    <input name="shippingmethod" id="shippingmethod" title="<?php //echo Mage::helper('quote2sales')->__('shippingmethod') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li>

             <li>    
                <label for="deliverydate"><?php //echo Mage::helper('quote2sales')->__('deliverylocation') ?></label>
                <div class="input-box">
                    <input name="deliverydate" id="deliverydate" title="<?php //echo Mage::helper('quote2sales')->__('deliverydate') ?>" value="" class="" type="text" maxlength="15" />
                </div>
            </li> -->

            <!-- -->

            <!-- If the product wise quote request is generated -->
            
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('quote2sales')->__('Comment') ?></label>
                <div class="input-box">

                    <!-- Displaying the product name if RFQ is selected from the product -->
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('quote2sales')->__('Comment') ?>" class="required-entry input-text validate-xss-comment validate-comment" cols="5" rows="3"></textarea>
                    <input type="hidden" id="product_id" name="product_id" value="<?php echo $_product->getId(); ?>">
                </div>
            </li>
        </ul>
        </div>
</div>
        <div class="col-lg-6">
            <ul>
            <?php if ($_product->getName()) : ?> 
                <li>
                    <label><?php echo Mage::helper('quote2sales')->__('Product for Quote:  ' . $_product->getName()) ?></label>
                </li>
             <?php endif; ?>

             <?php if ($_product->getDescription()) : ?> 
                <li>
                    <label><?php echo Mage::helper('quote2sales')->__('Description:  ' . $_product->getDescription()) ?></label>
                </li>
                <?php endif; ?>

                <?php if ($_product->getPrice()) : ?> 
                <li>
                    <label><?php echo Mage::helper('quote2sales')->__('Price: ₹  ' . $_product->getPrice()) ?></label>
                </li>
                <?php endif; ?>

                <?php if ($_product->getImage()) : ?> 
                <?php 

                    $url = Mage::getBaseUrl('media').'catalog/product/'.$_product->getImage(); 
                ?>
                <img src = "<?php echo $url;?>" width ="50" height="50"/>
                <?php endif; ?>

                <?php if ($_product->getMinimumOrderQuantity()) : ?> 
                <li>
                    <label><?php echo Mage::helper('quote2sales')->__('Minimum Order Quantity:  ' . $min ) ?></label>
                </li>
                <?php endif; ?>
                
                <?php if ($_product->getMinimumOrderUnit()) : ?> 
                <li>
                    <label><?php echo Mage::helper('quote2sales')->__('Minimum Order Unit:  ' . $_product->getMinimumOrderUnit()) ?></label>
                </li>
                <?php endif; ?>

                <?php if ($_product->getManufacturerProductCode()) : ?> 
                <li>
                    <label><?php echo Mage::helper('quote2sales')->__('Manufacturer Product Code:  ' . $_product->getManufacturerProductCode()) ?></label>
                </li>
                <?php endif; ?>
            </ul>
        </div>

    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('quote2sales')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('quote2sales')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('quote2sales')->__('Submit') ?></span></span></button>
    </div>
</form>
</div>
</div>
<script type="text/javascript">

//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>

//Validation for comment field 
    Validation.add('validate-xss-comment', 'Please enter valid data.', function (v) {
        return Validation.get('IsEmpty').test(v) || /^[a-zA-Z0-9\ \&\;\_\.\,\!\#\-\(\)\$\%\+\=\?\@\:\n\'/\"/\/\*\\]+$/.test(v)
    })

    Validation.add('validate-comment', 'Please enter valid data.', function (v) {
        return Validation.get('IsEmpty').test(v) || /^[a-zA-Z0-9\ \@=\-.&$%?)_+*(#!,'\n\;'/\:"]+$/.test(v)
    })

    Validation.add('validate-telephone', 'Please use numbers only in this field.', function (v) {
        return Validation.get('IsEmpty').test(v) || !/[^\d]/.test(v);
    })

    Validation.add('validate-phonenumber', 'Please use numbers only in this field.', function (v) {
        return Validation.get('IsEmpty').test(v) || (!isNaN(parseNumber(v)) && !/^\s+$/.test(parseNumber(v)));
    })

</script>
