<?php
/**
 * Created by PhpStorm.
 * User: Vu Van Phan
 * Date: 31-01-2015
 * Time: 7:57
 */
?>
<tr>
    <td class="" style="" colspan="2">
        <div>
            <div id="layer_animation_preview" class="">
                <div id="CmrContent" class="cameraContent">
                    <div id="animation_preview" class="" style="">
                        <?php
                            echo Mage::helper('sm_cameraslide')->__('LAYER SAMPLE')
                        ?>
                    </div>

                    <div id="animation_control">
                        <span class="ico on" title="<?php echo Mage::helper('sm_cameraslide')->__('Toogle autorun') ?>" onclick="return CmrSl.toggleAutotun()"></span>
                    </div>
                </div>
            </div>
            <?php if($note = $this->getElement()->getNote()): ?>
                <p class="note" id="note_delay" style="">
                    <span>
                        <?php echo $note; ?>
                    </span>
                </p>
            <?php endif ?>
        </div>
    </td>
</tr>