
<div>
    <form action="<?php echo Mage::getBaseUrl() . 'shoppinglist/index/createShoppingList' ?>" method="post"
          id="form-shopp" name="form-shopp">
        <div class="clearfix">
            <div class="pull-right">
                <button class="button" title="Create New List" type="button" id="btn_create_shop_list">
                    <span><span>Create New List</span></span>
                </button>
            </div>
            <div class="pull-right">
                <input type="text" class="in-shopp input-text small-input-text required-entry validate-value-exist-depend-on" name="shopplist[list_name]" value="" id="list_name" data-model="shoppinglist/shoppinglist" data-field="list_name" data-depend-on="company_id" data-depend-value="<?php echo $this->getCurrentCompanyId() ?>" />
                <input type="hidden" class="input-text" name="shopplist[company_id]" value="<?php echo $this->getCurrentCompanyId() ?>" />
            </div>
        </div>
    </form>
</div>
<div id="shopp_list_data">
    <?php echo $this->getChildHtml('shopp_list_data'); ?>
</div>
<script type="text/javascript">
    //<![CDATA[
  Validation.add('validate-value-exist-depend-on','Already Exist!',function(v,elm){
      var jelm=jQuery("#"+elm.id);
      var model=jelm.data('model');
      var field=jelm.data('field');
      var value=jelm.val();
      var depend_on=jelm.data('depend-on');
      var depend_value=jelm.data('depend-value');
      var is_true=false;
      jQuery.ajax({
          url: '<?php echo Mage::getBaseUrl()."kitnekaa_core/validation/validateDependUnique" ?>',
          type:'POST',
          async:false,
          data: {model:model,field:field,value:value,depend_on:depend_on,depend_value:depend_value},
          success: function (response) {
            if(parseInt(response))
            {
             // alert("sdasd");
                is_true= true;
            }
            else
            {
                is_true=false;
            }
          }
      });
    return is_true;
    });

    var dataForm = new VarienForm('form-shopp', true);

    jQuery(function(){
        var validator = new Validation('form-shopp');
        jQuery("#btn_create_shop_list").on('click',function(){
            var form_shopp=jQuery("#form-shopp");

            if(validator.validate()){
                var url=form_shopp.attr('action');
                jQuery("#shopp_list_data").html('');
                jQuery("#loading1").show();
                jQuery.ajax({
                    url: url,
                    type:'POST',
                    data: form_shopp.serialize(),
                    success: function (response) {
                        var data=jQuery.parseJSON(response);
                        jQuery("#block_cmb_shopp_lists").html(data.select);
                        var list_id=jQuery("#cmb_shopp_lists").val();
                        jQuery("#current_list_id").val(list_id);
                        populateItemsInList(list_id);
                        jQuery("#shopp_list_data").html(data.block);
                        document.getElementById("form-shopp").reset();
                        jQuery("#loading1").hide();
                        showSuccessMsg(data.msg);
                        //alert(data.msg);
                    }
                });

            }
        });

        jQuery(".in-shopp").on('keypress',function(e){
            if (e.which == 13) {
                e.preventDefault();
                jQuery("#btn_create_shop_list").trigger('click');
            }
        });
    });
    //]]>
</script>