<div>
    <span>Mention the addresses for selected products quote! </span>
    <form method="post" class="shopp_form_items" >
        <label for="billing_address_id"><?php echo Mage::helper('quote2sales')->__('Billing Address') ?></label>
        <div class="input-box">
            <?php echo Mage::helper('quote2sales')->getAddressesHtmlSelect('request_quote[billing_address_id]'); ?>
        </div>


        <label for="deliverylocation"><?php echo Mage::helper('quote2sales')->__('Delivery Location') ?></label>
        <div class="input-box">
            <?php echo Mage::helper('quote2sales')->getAddressesHtmlSelect('request_quote[deliverylocation]'); ?>
        </div>
        <button type="button" onclick="submitMultiQuote()" class="shop-quote kit_popup_btn">Submit Quote Request</button>
    </form>
</div>


