<div style="display: none;">
    <div id="kit_file_popup_main" class="kit_file_pop clearfix">
        <div id="loading_1" style="text-align: center;display: none" class="item-fields kit_file_content">
            <img class="v-middle" alt="" src="<?php echo $this->getSkinUrl('sm/cartpro/images/ajax-loader-tr.gif') ?>">
            <span><?php echo $this->__('Loading, please wait...'); ?></span>
        </div>
        <div id="kit_file_popup" class="item-fields kit_file_content">
        </div>
    </div>
</div>