<div class="seller-page">
	<div class="sell-banner">
		<ul class="sell-points">
			<li>1. Register on Kitnekaa.com</li>
			<li>2. Provide Product Catalog</li>
			<li>3. Sell</li>
			<li>4. Receive Payments</li>
		</ul>
		<div class="sell-register">
			<form>
				<h2>REGISTER NOW</h2>
				<input type="text" class="input-text" placeholder="Name">
				<input type="text" class="input-text" placeholder="E-mail address">
				<input type="text" class="input-text" placeholder="Mobile number">
				<input type="button" class="seller-register-button" value="Register">	
			</form>
			<p>OR CALL ON - 1800 3000 2004</p>
		</div>
		<img border="0" src="<?php echo $this->getSkinUrl('images/seller-banner.jpg') ?>" alt="Kitnekaa" title="Seller"/>
	</div>

	<div class="sell-offer">
		<div class="col-lg-3 sell-offer-inner">4500 +<span>Businesses</span></div>
		<div class="col-lg-3 sell-offer-inner">10 days<span>process payment</span></div>
		<div class="col-lg-3 sell-offer-inner">Sell<span>process online or offline</span></div>
		<div class="col-lg-3 sell-offer-inner">100,000+<span>products on the website</span></div>
	</div>

	<div class="clr"></div>
	<div class="sell-brands-section col-lg-12">
		<div class="row">
			<p>These brands enjoy the following benefits</p>
			<ul id="flexiselDemo1"> 
			    <li><span><img src="<?php echo $this->getSkinUrl('images/brands/cmt-orange.jpg') ?>" /></span></li>
			    <li><span><img src="<?php echo $this->getSkinUrl('images/brands/stark.jpg') ?>" /></span></li>
			    <li><span><img src="<?php echo $this->getSkinUrl('images/brands/mirka.jpg') ?>" /></span></li>
			    <li><span><img src="<?php echo $this->getSkinUrl('images/brands/tigra.jpg') ?>" /></span></li>
			    <li><span><img src="<?php echo $this->getSkinUrl('images/brands/total.jpg') ?>" /></span></li>                                                        
			</ul>
		</div>
	</div>

	<div class="sell-benefits col-lg-12">
		<div class="row">
			<h2 class="sell-title">BENEFITS</h2>

			<div class="col-sm-6 benefit-info">
				<div class="ben-ic"><img src="<?php echo $this->getSkinUrl('images/industry-focus.png') ?>" /></div>
				<div class="ben-txt">
					<h3>Industry Focus</h3>
					<p>Kitnekaa is a specialist B2B eCommerce portal that focusses on the woodworking industry. We have over 25 years of experience and are focused on reaching out to every player in this space – either to meet their purchase or sell needs. </p>
				</div>
			</div>
			<div class="col-sm-6 benefit-info">
				<div class="ben-ic"><img src="<?php echo $this->getSkinUrl('images/outcome-oriented.png') ?>" /></div>
				<div class="ben-txt">
					<h3>Business to Business Focus</h3>
					<p>B2B means that unlike other portals, we do not have millions of customers to whom we need to sell once a year – but we have thousands of customers to whom we will sell to millions of time every year.</p>
				</div>
			</div>
			<div class="col-sm-6 benefit-info">
				<div class="ben-ic"><img src="<?php echo $this->getSkinUrl('images/business-focus.png') ?>" /></div>
				<div class="ben-txt">
					<h3>Outcome Oriented</h3>
					<p>We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.</p>
				</div>
			</div>
			<div class="col-sm-6 benefit-info">
				<div class="ben-ic"><img src="<?php echo $this->getSkinUrl('images/industry-focus.png') ?>" /></div>
				<div class="ben-txt">
					<h3>24x7x365 PR shop</h3>
					<p>Once your products are online, Kitnekaa.com and our marketing campaigns spanning exhibitions, search engines, road shows, targeted campaigns and tele-callers, reach out to potential customers every minute of the day. We are your very own Public Relations factory.</p>
				</div>
			</div>
			<div class="col-sm-6 benefit-info">
				<div class="ben-ic"><img src="<?php echo $this->getSkinUrl('images/pr-shop.png') ?>" /></div>
				<div class="ben-txt">
					<h3>Repeat business</h3>
					<p>Once a customer purchases from Kitnekaa.com, our account management team follows up for repeat business after understanding the purchase patterns of the customer. </p>
				</div>
			</div>
			<div class="col-sm-6 benefit-info">
				<div class="ben-ic"><img src="<?php echo $this->getSkinUrl('images/cost-reduction.png') ?>" /></div>
				<div class="ben-txt">
					<h3>Cost Reduction</h3>
					<p>Wait a minute! Isn’t all that why you need to hire and maintain an army of sales personnel? We allow you to rationalize such costs and yet at the same time scale your business.
</p>
				</div>
			</div>
		</div>
	</div>

	<div class="sell-faq">
		<h2 class="sell-title">FAQS</h2>
		<div class="accordion-default">
			<div class="accord-sec">
				<div class="accord-tab">Do I need to display my products’ price on Kitnekaa.com?</div>
				<div class="accord-content">
					We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.
				</div>
			</div>
			<div class="accord-sec">
				<div class="accord-tab">If I don’t display prices, how will the sale process work?</div>
				<div class="accord-content">
					We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.
				</div>
			</div>
			<div class="accord-sec">
				<div class="accord-tab">How is Shipping managed?</div>
				<div class="accord-content">
					We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.
				</div>
			</div>
			<div class="accord-sec">
				<div class="accord-tab">Who bears Shipping costs then?</div>
				<div class="accord-content">
					We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.
				</div>
			</div>
			<div class="accord-sec">
				<div class="accord-tab">Do I transfact with the Buyer directly?</div>
				<div class="accord-content">
					We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.
				</div>
			</div>
			<div class="accord-sec">
				<div class="accord-tab">In some cases, you will need to transact with the Buyer directly. In most cases, our Procurement Executive will assist you through the process</div>
				<div class="accord-content">
					We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.We do not charge you joining fees. In fact we make money ONLY WHEN YOU DO. This pushes us hard to try and understand your products better so that we can sell them better.
				</div>
			</div>
		</div>

		<div class="testimonial-sec">
			<h2 class="sell-title">TESTIMONIALS</h2>
			<div id="carousel-testimonial-generic" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			    <li data-target="#carousel-testimonial-generic" data-slide-to="0" class="active"></li>
			    <li data-target="#carousel-testimonial-generic" data-slide-to="1"></li>
			    <li data-target="#carousel-testimonial-generic" data-slide-to="2"></li>
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" role="listbox">
			    <div class="item active">
			        <div class="col-sm-4 testi-profile-pic"></div>
			        <div class="col-sm-8 testi-profile-txt">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
			    </div>
			    <div class="item">
			        <div class="col-sm-4 testi-profile-pic"></div>
			        <div class="col-sm-8 testi-profile-txt">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
			    </div>
			  </div>

			  <!-- Controls -->
			  <a class="left carousel-control" href="#carousel-testimonial-generic" role="button" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#carousel-testimonial-generic" role="button" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
			</div>
		</div>

	</div>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.flexisel.js') ?>"></script>
<script type="text/javascript">
    jQuery(window).load(function() {
        jQuery("#flexiselDemo1").flexisel({
        visibleItems: 5,
        enableResponsiveBreakpoints: true,
        responsiveBreakpoints: { 
            portrait: { 
                changePoint:480,
                visibleItems: 1
            }, 
            landscape: { 
                changePoint:640,
                visibleItems: 2
            },
            tablet: { 
                changePoint:768,
                visibleItems: 3
            }
        }
    });
    });
</script>