<script type="text/javascript">
  jQuery(function(){
      jQuery('#datetimepickerchq').datetimepicker({
          format: 'DD-MM-YYYY',
           useCurrent: false, //Important! See issue #1075
           //dateFormat: 'dd-mm-yy',
      });
  });
</script>


<div class="form-list checkout-payment-innerdddiv" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <div>
    <label><?php echo $this->__('Account Name') ?></label>
    <span><?php echo $this->__(' - KITNEKAA ON-LINE TRADING PRIVATE LIMITED') ?>
    </span>
  </div> 
  <div>
    <label><?php echo $this->__('Account Number') ?></label>
    <span><?php echo $this->__(' - 50200014501304') ?></span>
  </div> 
   <div>
    <label><?php echo $this->__('Bank Name') ?></label>
    <span><?php echo $this->__(' - HDFC Bank') ?></span>
  </div> 
  <div>
    <label><?php echo $this->__('Account Type ') ?></label>
    <span><?php echo $this->__(' - Current A/c') ?></span>
  </div>
  <div>
    <label><?php echo $this->__('Cheque Number') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Cheque Number') ?>" name="payment[cust_chq_number]"  class="input-text required-entry validate-digits validate-maxlength maximum-length-6 validate-minlength minimum-length-6"
      value="<?php echo $this->htmlEscape($this->getInfoData('cust_chq_number')) ?>" />
    </span>
  </div>
  <div>
    <label><?php echo $this->__('Bank Name') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Bank Name') ?>" name="payment[cust_bank_name]"  id="bank_name_chq"
      class="input-text required-entry validate-alpha-space" value="<?php echo $this->htmlEscape($this->getInfoData('cust_bank_name')) ?>" />
    </span>
  </div>
  <div>
    <label><?php echo $this->__('Branch Name') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Branch Name') ?>" name="payment[cust_branch_name]" id="branch_name_chq"
      class="input-text required-entry validate-alpha-space" value="<?php echo $this->htmlEscape($this->getInfoData('cust_branch_name')) ?>" />
    </span>
  </div>
  <div>
    <label><?php echo $this->__('Date Of Transaction') ?>*</label>   
    <span class="payment_datapicker">
      <div class='input-group date' id='datetimepickerchq'>
         <input type='text' class="form-control input-text required-entry"  id="chq_date" title="<?php echo $this->__('Date of transaction') ?>"  name="payment[cust_trans_date]" value="<?php echo $this->htmlEscape($this->getInfoData('cust_trans_date')) ?>"/>
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
      </div>
    </span>  
  </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
