
<ul class="form-list checkout-payment-innerdddiv" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">

  <li>
    <label><?php echo $this->__('Cheque Number') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Cheque Number') ?>" name="payment[cust_chq_number]"  class="input-text required-entry validate-digits validate-maxlength maximum-length-6 validate-minlength minimum-length-6" style="margin-left: 50px; margin-bottom: 10px; margin-top: 10px;" 
      value="<?php echo $this->htmlEscape($this->getInfoData('cust_chq_number')) ?>" />
    </span>
  </li>
  <li>
    <label><?php echo $this->__('Bank Name') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Bank Name') ?>" name="payment[cust_bank_name]"  id="bank_name_chq" style="margin-left: 75px; margin-bottom: 10px; margin-top: 10px;" 
      class="input-text required-entry validate-alpha-space" value="<?php echo $this->htmlEscape($this->getInfoData('cust_bank_name')) ?>" />
    </span>
  </li>
  <li>
    <label><?php echo $this->__('Branch Name') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Branch Name') ?>" name="payment[cust_branch_name]" id="branch_name_chq" style="margin-left: 65px; margin-bottom: 10px; margin-top: 10px;" 
      class="input-text required-entry validate-alpha-space" value="<?php echo $this->htmlEscape($this->getInfoData('cust_branch_name')) ?>" />
    </span>
  </li>
  <li>
    <label><?php echo $this->__('Date Of Transaction') ?>*</label>   
    <span class="payment_datapicker">
    
           <input name="payment[cust_trans_date]" id="trans_date_chq" value="<?php echo $this->htmlEscape($this->getInfoData('cust_trans_date'))?>" tabindex="1" class=" input-text required-entry validate-date" style="width:110px !important; margin-left: 32px; margin-bottom: 10px; margin-top: 10px;" type="text"/> 
          <span>
              <img src="http://localhost/latte/applications/magneto/woodworks_demo/skin/adminhtml/default/default/images/grid-cal.gif" alt="" class="v-middle" id="from_date_chq" title="Select Date" style=""/>
          </span>
       <script type="text/javascript">
                                //<![CDATA[
                                    Calendar.setup({
                                        inputField: "trans_date_chq",
                                        ifFormat: "%e/%m/%Y",
                                        showsTime: false,
                                        button: "from_date_chq",
                                        align: "Bl",
                                        singleClick : true,
                                        disableFunc: function(date) {
var now= new Date();
if(date.getFullYear() < now.getFullYear()) { return true; }
if(date.getFullYear() == now.getFullYear()) { if(date.getMonth() < now.getMonth()) { return true; } }
if(date.getMonth() == now.getMonth()) { if(date.getDate() < now.getDate()) { return true; } }
},
                                    });
                                //]]>
                                </script>
    </span>  
  </li>
</ul>
<!-- <div>
    <?php //echo $this->getMethod()->getConfigData('message');?>
</div> -->
