<?php
/*------------------------------------------------------------------------
 # SM Tab Listing - Version 1.0
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
?>
<?php 
	//$cms_id = Mage::getSingleton('cms/page')->getIdentifier();
?>
<!-- <div class="respl-tabs-wrap">
	<ul class="respl-tabs cf">
		<?php foreach($list as $tab){ ?>
		<li class="respl-tab <?php echo isset($tab->sel)?'  tab-sel tab-loaded':''; ?>" data-type="<?php echo $options->type_tab_display; ?>" config-categoryid="<?php echo $options->product_category; ?>" data-category-id="<?php echo $tab->id; ?>" data-order-id="<?php echo $tab->orderid; ?>" data-active-content=".items-category-<?php echo ($tab->id == "*")?'all':$tab->id; ?>" data-cmspage-id="<?php echo $cms_id; ?>">
			<span class="respl-tab-label"><?php echo $tab->title; ?>
			</span>
		</li>
		<?php }?>
	</ul>
</div> -->

